interface SystemUser_Base extends WebEntity {
  accessmode?: systemuser_accessmode | null;
  activedirectoryguid?: string | null;
  address1_addressid?: string | null;
  address1_addresstypecode?: systemuser_address1_addresstypecode | null;
  address1_city?: string | null;
  address1_composite?: string | null;
  address1_country?: string | null;
  address1_county?: string | null;
  address1_fax?: string | null;
  address1_latitude?: number | null;
  address1_line1?: string | null;
  address1_line2?: string | null;
  address1_line3?: string | null;
  address1_longitude?: number | null;
  address1_name?: string | null;
  address1_postalcode?: string | null;
  address1_postofficebox?: string | null;
  address1_shippingmethodcode?: systemuser_address1_shippingmethodcode | null;
  address1_stateorprovince?: string | null;
  address1_telephone1?: string | null;
  address1_telephone2?: string | null;
  address1_telephone3?: string | null;
  address1_upszone?: string | null;
  address1_utcoffset?: number | null;
  address2_addressid?: string | null;
  address2_addresstypecode?: systemuser_address2_addresstypecode | null;
  address2_city?: string | null;
  address2_composite?: string | null;
  address2_country?: string | null;
  address2_county?: string | null;
  address2_fax?: string | null;
  address2_latitude?: number | null;
  address2_line1?: string | null;
  address2_line2?: string | null;
  address2_line3?: string | null;
  address2_longitude?: number | null;
  address2_name?: string | null;
  address2_postalcode?: string | null;
  address2_postofficebox?: string | null;
  address2_shippingmethodcode?: systemuser_address2_shippingmethodcode | null;
  address2_stateorprovince?: string | null;
  address2_telephone1?: string | null;
  address2_telephone2?: string | null;
  address2_telephone3?: string | null;
  address2_upszone?: string | null;
  address2_utcoffset?: number | null;
  applicationid?: string | null;
  applicationiduri?: string | null;
  azureactivedirectoryobjectid?: string | null;
  caltype?: systemuser_caltype | null;
  createdon?: Date | null;
  defaultfilterspopulated?: boolean | null;
  defaultodbfoldername?: string | null;
  disabledreason?: string | null;
  displayinserviceviews?: boolean | null;
  domainname?: string | null;
  emailrouteraccessapproval?: systemuser_emailrouteraccessapproval | null;
  employeeid?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  firstname?: string | null;
  fullname?: string | null;
  governmentid?: string | null;
  homephone?: string | null;
  identityid?: number | null;
  importsequencenumber?: number | null;
  incomingemaildeliverymethod?: systemuser_incomingemaildeliverymethod | null;
  internalemailaddress?: string | null;
  invitestatuscode?: systemuser_invitestatuscode | null;
  isactivedirectoryuser?: boolean | null;
  isdisabled?: boolean | null;
  isemailaddressapprovedbyo365admin?: boolean | null;
  isintegrationuser?: boolean | null;
  islicensed?: boolean | null;
  issyncwithdirectory?: boolean | null;
  jobtitle?: string | null;
  lastname?: string | null;
  latestupdatetime?: Date | null;
  middlename?: string | null;
  mobilealertemail?: string | null;
  mobilephone?: string | null;
  modifiedon?: Date | null;
  msdyn_gdproptout?: boolean | null;
  nickname?: string | null;
  organizationid?: string | null;
  outgoingemaildeliverymethod?: systemuser_outgoingemaildeliverymethod | null;
  overriddencreatedon?: Date | null;
  passporthi?: number | null;
  passportlo?: number | null;
  personalemailaddress?: string | null;
  photourl?: string | null;
  preferredaddresscode?: systemuser_preferredaddresscode | null;
  preferredemailcode?: systemuser_preferredemailcode | null;
  preferredphonecode?: systemuser_preferredphonecode | null;
  processid?: string | null;
  salutation?: string | null;
  setupuser?: boolean | null;
  sharepointemailaddress?: string | null;
  skills?: string | null;
  stageid?: string | null;
  systemuserid?: string | null;
  timezoneruleversionnumber?: number | null;
  title?: string | null;
  traversedpath?: string | null;
  userlicensetype?: number | null;
  userpuid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  windowsliveid?: string | null;
  yammeremailaddress?: string | null;
  yammeruserid?: string | null;
}
interface SystemUser_Relationships {
  createdby_connection?: Connection_Result[] | null;
  lk_PostFollow_createdby?: PostFollow_Result[] | null;
  lk_connectionbase_createdonbehalfby?: Connection_Result[] | null;
  lk_connectionbase_modifiedonbehalfby?: Connection_Result[] | null;
  lk_hr_casesubtype_createdby?: hr_CaseSubType_Result[] | null;
  lk_hr_casesubtype_createdonbehalfby?: hr_CaseSubType_Result[] | null;
  lk_hr_casesubtype_modifiedby?: hr_CaseSubType_Result[] | null;
  lk_hr_casesubtype_modifiedonbehalfby?: hr_CaseSubType_Result[] | null;
  lk_hr_casetype_createdby?: hr_CaseType_Result[] | null;
  lk_hr_casetype_createdonbehalfby?: hr_CaseType_Result[] | null;
  lk_hr_casetype_modifiedby?: hr_CaseType_Result[] | null;
  lk_hr_casetype_modifiedonbehalfby?: hr_CaseType_Result[] | null;
  lk_hr_hrcase_createdby?: hr_HRCase_Result[] | null;
  lk_hr_hrcase_createdonbehalfby?: hr_HRCase_Result[] | null;
  lk_hr_hrcase_modifiedby?: hr_HRCase_Result[] | null;
  lk_hr_hrcase_modifiedonbehalfby?: hr_HRCase_Result[] | null;
  lk_hr_questionandanswers_createdby?: hr_QuestionandAnswers_Result[] | null;
  lk_hr_questionandanswers_createdonbehalfby?: hr_QuestionandAnswers_Result[] | null;
  lk_hr_questionandanswers_modifiedby?: hr_QuestionandAnswers_Result[] | null;
  lk_hr_questionandanswers_modifiedonbehalfby?: hr_QuestionandAnswers_Result[] | null;
  lk_post_createdby?: Post_Result[] | null;
  lk_post_createdonbehalfby?: Post_Result[] | null;
  lk_post_modifiedby?: Post_Result[] | null;
  lk_post_modifiedonbehalfby?: Post_Result[] | null;
  lk_postfollow_createdonbehalfby?: PostFollow_Result[] | null;
  lk_systemuser_createdonbehalfby?: SystemUser_Result[] | null;
  lk_systemuser_modifiedonbehalfby?: SystemUser_Result[] | null;
  lk_systemuserbase_createdby?: SystemUser_Result[] | null;
  lk_systemuserbase_modifiedby?: SystemUser_Result[] | null;
  lk_templatebase_createdby?: Template_Result[] | null;
  lk_templatebase_createdonbehalfby?: Template_Result[] | null;
  lk_templatebase_modifiedby?: Template_Result[] | null;
  lk_templatebase_modifiedonbehalfby?: Template_Result[] | null;
  modifiedby_connection?: Connection_Result[] | null;
  system_user_email_templates?: Template_Result[] | null;
  systemuser_PostFollows?: PostFollow_Result[] | null;
  systemuser_connections1?: Connection_Result[] | null;
  systemuser_connections2?: Connection_Result[] | null;
  user_hr_casesubtype?: hr_CaseSubType_Result[] | null;
  user_hr_casetype?: hr_CaseType_Result[] | null;
  user_hr_hrcase?: hr_HRCase_Result[] | null;
  user_hr_questionandanswers?: hr_QuestionandAnswers_Result[] | null;
  user_owner_postfollows?: PostFollow_Result[] | null;
  user_parent_user?: SystemUser_Result[] | null;
}
interface SystemUser extends SystemUser_Base, SystemUser_Relationships {
  businessunitid_bind$businessunits?: string | null;
  calendarid_bind$calendars?: string | null;
  mobileofflineprofileid_bind$mobileofflineprofiles?: string | null;
  parentsystemuserid_bind$systemusers?: string | null;
  positionid_bind$positions?: string | null;
  queueid_bind$queues?: string | null;
  siteid_bind$sites?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  territoryid_bind$territories?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface SystemUser_Create extends SystemUser {
}
interface SystemUser_Update extends SystemUser {
}
interface SystemUser_Select {
  accessmode: WebAttribute<SystemUser_Select, { accessmode: systemuser_accessmode | null }, { accessmode_formatted?: string }>;
  activedirectoryguid: WebAttribute<SystemUser_Select, { activedirectoryguid: string | null }, {  }>;
  address1_addressid: WebAttribute<SystemUser_Select, { address1_addressid: string | null }, {  }>;
  address1_addresstypecode: WebAttribute<SystemUser_Select, { address1_addresstypecode: systemuser_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
  address1_city: WebAttribute<SystemUser_Select, { address1_city: string | null }, {  }>;
  address1_composite: WebAttribute<SystemUser_Select, { address1_composite: string | null }, {  }>;
  address1_country: WebAttribute<SystemUser_Select, { address1_country: string | null }, {  }>;
  address1_county: WebAttribute<SystemUser_Select, { address1_county: string | null }, {  }>;
  address1_fax: WebAttribute<SystemUser_Select, { address1_fax: string | null }, {  }>;
  address1_latitude: WebAttribute<SystemUser_Select, { address1_latitude: number | null }, {  }>;
  address1_line1: WebAttribute<SystemUser_Select, { address1_line1: string | null }, {  }>;
  address1_line2: WebAttribute<SystemUser_Select, { address1_line2: string | null }, {  }>;
  address1_line3: WebAttribute<SystemUser_Select, { address1_line3: string | null }, {  }>;
  address1_longitude: WebAttribute<SystemUser_Select, { address1_longitude: number | null }, {  }>;
  address1_name: WebAttribute<SystemUser_Select, { address1_name: string | null }, {  }>;
  address1_postalcode: WebAttribute<SystemUser_Select, { address1_postalcode: string | null }, {  }>;
  address1_postofficebox: WebAttribute<SystemUser_Select, { address1_postofficebox: string | null }, {  }>;
  address1_shippingmethodcode: WebAttribute<SystemUser_Select, { address1_shippingmethodcode: systemuser_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
  address1_stateorprovince: WebAttribute<SystemUser_Select, { address1_stateorprovince: string | null }, {  }>;
  address1_telephone1: WebAttribute<SystemUser_Select, { address1_telephone1: string | null }, {  }>;
  address1_telephone2: WebAttribute<SystemUser_Select, { address1_telephone2: string | null }, {  }>;
  address1_telephone3: WebAttribute<SystemUser_Select, { address1_telephone3: string | null }, {  }>;
  address1_upszone: WebAttribute<SystemUser_Select, { address1_upszone: string | null }, {  }>;
  address1_utcoffset: WebAttribute<SystemUser_Select, { address1_utcoffset: number | null }, {  }>;
  address2_addressid: WebAttribute<SystemUser_Select, { address2_addressid: string | null }, {  }>;
  address2_addresstypecode: WebAttribute<SystemUser_Select, { address2_addresstypecode: systemuser_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
  address2_city: WebAttribute<SystemUser_Select, { address2_city: string | null }, {  }>;
  address2_composite: WebAttribute<SystemUser_Select, { address2_composite: string | null }, {  }>;
  address2_country: WebAttribute<SystemUser_Select, { address2_country: string | null }, {  }>;
  address2_county: WebAttribute<SystemUser_Select, { address2_county: string | null }, {  }>;
  address2_fax: WebAttribute<SystemUser_Select, { address2_fax: string | null }, {  }>;
  address2_latitude: WebAttribute<SystemUser_Select, { address2_latitude: number | null }, {  }>;
  address2_line1: WebAttribute<SystemUser_Select, { address2_line1: string | null }, {  }>;
  address2_line2: WebAttribute<SystemUser_Select, { address2_line2: string | null }, {  }>;
  address2_line3: WebAttribute<SystemUser_Select, { address2_line3: string | null }, {  }>;
  address2_longitude: WebAttribute<SystemUser_Select, { address2_longitude: number | null }, {  }>;
  address2_name: WebAttribute<SystemUser_Select, { address2_name: string | null }, {  }>;
  address2_postalcode: WebAttribute<SystemUser_Select, { address2_postalcode: string | null }, {  }>;
  address2_postofficebox: WebAttribute<SystemUser_Select, { address2_postofficebox: string | null }, {  }>;
  address2_shippingmethodcode: WebAttribute<SystemUser_Select, { address2_shippingmethodcode: systemuser_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
  address2_stateorprovince: WebAttribute<SystemUser_Select, { address2_stateorprovince: string | null }, {  }>;
  address2_telephone1: WebAttribute<SystemUser_Select, { address2_telephone1: string | null }, {  }>;
  address2_telephone2: WebAttribute<SystemUser_Select, { address2_telephone2: string | null }, {  }>;
  address2_telephone3: WebAttribute<SystemUser_Select, { address2_telephone3: string | null }, {  }>;
  address2_upszone: WebAttribute<SystemUser_Select, { address2_upszone: string | null }, {  }>;
  address2_utcoffset: WebAttribute<SystemUser_Select, { address2_utcoffset: number | null }, {  }>;
  applicationid: WebAttribute<SystemUser_Select, { applicationid: string | null }, {  }>;
  applicationiduri: WebAttribute<SystemUser_Select, { applicationiduri: string | null }, {  }>;
  azureactivedirectoryobjectid: WebAttribute<SystemUser_Select, { azureactivedirectoryobjectid: string | null }, {  }>;
  businessunitid_guid: WebAttribute<SystemUser_Select, { businessunitid_guid: string | null }, { businessunitid_formatted?: string }>;
  calendarid_guid: WebAttribute<SystemUser_Select, { calendarid_guid: string | null }, { calendarid_formatted?: string }>;
  caltype: WebAttribute<SystemUser_Select, { caltype: systemuser_caltype | null }, { caltype_formatted?: string }>;
  createdby_guid: WebAttribute<SystemUser_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<SystemUser_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<SystemUser_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  defaultfilterspopulated: WebAttribute<SystemUser_Select, { defaultfilterspopulated: boolean | null }, {  }>;
  defaultmailbox_guid: WebAttribute<SystemUser_Select, { defaultmailbox_guid: string | null }, { defaultmailbox_formatted?: string }>;
  defaultodbfoldername: WebAttribute<SystemUser_Select, { defaultodbfoldername: string | null }, {  }>;
  disabledreason: WebAttribute<SystemUser_Select, { disabledreason: string | null }, {  }>;
  displayinserviceviews: WebAttribute<SystemUser_Select, { displayinserviceviews: boolean | null }, {  }>;
  domainname: WebAttribute<SystemUser_Select, { domainname: string | null }, {  }>;
  emailrouteraccessapproval: WebAttribute<SystemUser_Select, { emailrouteraccessapproval: systemuser_emailrouteraccessapproval | null }, { emailrouteraccessapproval_formatted?: string }>;
  employeeid: WebAttribute<SystemUser_Select, { employeeid: string | null }, {  }>;
  entityimageid: WebAttribute<SystemUser_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<SystemUser_Select, { exchangerate: number | null }, {  }>;
  firstname: WebAttribute<SystemUser_Select, { firstname: string | null }, {  }>;
  fullname: WebAttribute<SystemUser_Select, { fullname: string | null }, {  }>;
  governmentid: WebAttribute<SystemUser_Select, { governmentid: string | null }, {  }>;
  homephone: WebAttribute<SystemUser_Select, { homephone: string | null }, {  }>;
  identityid: WebAttribute<SystemUser_Select, { identityid: number | null }, {  }>;
  importsequencenumber: WebAttribute<SystemUser_Select, { importsequencenumber: number | null }, {  }>;
  incomingemaildeliverymethod: WebAttribute<SystemUser_Select, { incomingemaildeliverymethod: systemuser_incomingemaildeliverymethod | null }, { incomingemaildeliverymethod_formatted?: string }>;
  internalemailaddress: WebAttribute<SystemUser_Select, { internalemailaddress: string | null }, {  }>;
  invitestatuscode: WebAttribute<SystemUser_Select, { invitestatuscode: systemuser_invitestatuscode | null }, { invitestatuscode_formatted?: string }>;
  isactivedirectoryuser: WebAttribute<SystemUser_Select, { isactivedirectoryuser: boolean | null }, {  }>;
  isdisabled: WebAttribute<SystemUser_Select, { isdisabled: boolean | null }, {  }>;
  isemailaddressapprovedbyo365admin: WebAttribute<SystemUser_Select, { isemailaddressapprovedbyo365admin: boolean | null }, {  }>;
  isintegrationuser: WebAttribute<SystemUser_Select, { isintegrationuser: boolean | null }, {  }>;
  islicensed: WebAttribute<SystemUser_Select, { islicensed: boolean | null }, {  }>;
  issyncwithdirectory: WebAttribute<SystemUser_Select, { issyncwithdirectory: boolean | null }, {  }>;
  jobtitle: WebAttribute<SystemUser_Select, { jobtitle: string | null }, {  }>;
  lastname: WebAttribute<SystemUser_Select, { lastname: string | null }, {  }>;
  latestupdatetime: WebAttribute<SystemUser_Select, { latestupdatetime: Date | null }, { latestupdatetime_formatted?: string }>;
  middlename: WebAttribute<SystemUser_Select, { middlename: string | null }, {  }>;
  mobilealertemail: WebAttribute<SystemUser_Select, { mobilealertemail: string | null }, {  }>;
  mobileofflineprofileid_guid: WebAttribute<SystemUser_Select, { mobileofflineprofileid_guid: string | null }, { mobileofflineprofileid_formatted?: string }>;
  mobilephone: WebAttribute<SystemUser_Select, { mobilephone: string | null }, {  }>;
  modifiedby_guid: WebAttribute<SystemUser_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<SystemUser_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<SystemUser_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_gdproptout: WebAttribute<SystemUser_Select, { msdyn_gdproptout: boolean | null }, {  }>;
  nickname: WebAttribute<SystemUser_Select, { nickname: string | null }, {  }>;
  organizationid: WebAttribute<SystemUser_Select, { organizationid: string | null }, {  }>;
  outgoingemaildeliverymethod: WebAttribute<SystemUser_Select, { outgoingemaildeliverymethod: systemuser_outgoingemaildeliverymethod | null }, { outgoingemaildeliverymethod_formatted?: string }>;
  overriddencreatedon: WebAttribute<SystemUser_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  parentsystemuserid_guid: WebAttribute<SystemUser_Select, { parentsystemuserid_guid: string | null }, { parentsystemuserid_formatted?: string }>;
  passporthi: WebAttribute<SystemUser_Select, { passporthi: number | null }, {  }>;
  passportlo: WebAttribute<SystemUser_Select, { passportlo: number | null }, {  }>;
  personalemailaddress: WebAttribute<SystemUser_Select, { personalemailaddress: string | null }, {  }>;
  photourl: WebAttribute<SystemUser_Select, { photourl: string | null }, {  }>;
  positionid_guid: WebAttribute<SystemUser_Select, { positionid_guid: string | null }, { positionid_formatted?: string }>;
  preferredaddresscode: WebAttribute<SystemUser_Select, { preferredaddresscode: systemuser_preferredaddresscode | null }, { preferredaddresscode_formatted?: string }>;
  preferredemailcode: WebAttribute<SystemUser_Select, { preferredemailcode: systemuser_preferredemailcode | null }, { preferredemailcode_formatted?: string }>;
  preferredphonecode: WebAttribute<SystemUser_Select, { preferredphonecode: systemuser_preferredphonecode | null }, { preferredphonecode_formatted?: string }>;
  processid: WebAttribute<SystemUser_Select, { processid: string | null }, {  }>;
  queueid_guid: WebAttribute<SystemUser_Select, { queueid_guid: string | null }, { queueid_formatted?: string }>;
  salutation: WebAttribute<SystemUser_Select, { salutation: string | null }, {  }>;
  setupuser: WebAttribute<SystemUser_Select, { setupuser: boolean | null }, {  }>;
  sharepointemailaddress: WebAttribute<SystemUser_Select, { sharepointemailaddress: string | null }, {  }>;
  siteid_guid: WebAttribute<SystemUser_Select, { siteid_guid: string | null }, { siteid_formatted?: string }>;
  skills: WebAttribute<SystemUser_Select, { skills: string | null }, {  }>;
  stageid: WebAttribute<SystemUser_Select, { stageid: string | null }, {  }>;
  systemuserid: WebAttribute<SystemUser_Select, { systemuserid: string | null }, {  }>;
  territoryid_guid: WebAttribute<SystemUser_Select, { territoryid_guid: string | null }, { territoryid_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<SystemUser_Select, { timezoneruleversionnumber: number | null }, {  }>;
  title: WebAttribute<SystemUser_Select, { title: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<SystemUser_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<SystemUser_Select, { traversedpath: string | null }, {  }>;
  userlicensetype: WebAttribute<SystemUser_Select, { userlicensetype: number | null }, {  }>;
  userpuid: WebAttribute<SystemUser_Select, { userpuid: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<SystemUser_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<SystemUser_Select, { versionnumber: number | null }, {  }>;
  windowsliveid: WebAttribute<SystemUser_Select, { windowsliveid: string | null }, {  }>;
  yammeremailaddress: WebAttribute<SystemUser_Select, { yammeremailaddress: string | null }, {  }>;
  yammeruserid: WebAttribute<SystemUser_Select, { yammeruserid: string | null }, {  }>;
}
interface SystemUser_Filter {
  accessmode: systemuser_accessmode;
  activedirectoryguid: XQW.Guid;
  address1_addressid: XQW.Guid;
  address1_addresstypecode: systemuser_address1_addresstypecode;
  address1_city: string;
  address1_composite: string;
  address1_country: string;
  address1_county: string;
  address1_fax: string;
  address1_latitude: number;
  address1_line1: string;
  address1_line2: string;
  address1_line3: string;
  address1_longitude: number;
  address1_name: string;
  address1_postalcode: string;
  address1_postofficebox: string;
  address1_shippingmethodcode: systemuser_address1_shippingmethodcode;
  address1_stateorprovince: string;
  address1_telephone1: string;
  address1_telephone2: string;
  address1_telephone3: string;
  address1_upszone: string;
  address1_utcoffset: number;
  address2_addressid: XQW.Guid;
  address2_addresstypecode: systemuser_address2_addresstypecode;
  address2_city: string;
  address2_composite: string;
  address2_country: string;
  address2_county: string;
  address2_fax: string;
  address2_latitude: number;
  address2_line1: string;
  address2_line2: string;
  address2_line3: string;
  address2_longitude: number;
  address2_name: string;
  address2_postalcode: string;
  address2_postofficebox: string;
  address2_shippingmethodcode: systemuser_address2_shippingmethodcode;
  address2_stateorprovince: string;
  address2_telephone1: string;
  address2_telephone2: string;
  address2_telephone3: string;
  address2_upszone: string;
  address2_utcoffset: number;
  applicationid: XQW.Guid;
  applicationiduri: string;
  azureactivedirectoryobjectid: XQW.Guid;
  businessunitid_guid: XQW.Guid;
  calendarid_guid: XQW.Guid;
  caltype: systemuser_caltype;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  defaultfilterspopulated: boolean;
  defaultmailbox_guid: XQW.Guid;
  defaultodbfoldername: string;
  disabledreason: string;
  displayinserviceviews: boolean;
  domainname: string;
  emailrouteraccessapproval: systemuser_emailrouteraccessapproval;
  employeeid: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  firstname: string;
  fullname: string;
  governmentid: string;
  homephone: string;
  identityid: number;
  importsequencenumber: number;
  incomingemaildeliverymethod: systemuser_incomingemaildeliverymethod;
  internalemailaddress: string;
  invitestatuscode: systemuser_invitestatuscode;
  isactivedirectoryuser: boolean;
  isdisabled: boolean;
  isemailaddressapprovedbyo365admin: boolean;
  isintegrationuser: boolean;
  islicensed: boolean;
  issyncwithdirectory: boolean;
  jobtitle: string;
  lastname: string;
  latestupdatetime: Date;
  middlename: string;
  mobilealertemail: string;
  mobileofflineprofileid_guid: XQW.Guid;
  mobilephone: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_gdproptout: boolean;
  nickname: string;
  organizationid: XQW.Guid;
  outgoingemaildeliverymethod: systemuser_outgoingemaildeliverymethod;
  overriddencreatedon: Date;
  parentsystemuserid_guid: XQW.Guid;
  passporthi: number;
  passportlo: number;
  personalemailaddress: string;
  photourl: string;
  positionid_guid: XQW.Guid;
  preferredaddresscode: systemuser_preferredaddresscode;
  preferredemailcode: systemuser_preferredemailcode;
  preferredphonecode: systemuser_preferredphonecode;
  processid: XQW.Guid;
  queueid_guid: XQW.Guid;
  salutation: string;
  setupuser: boolean;
  sharepointemailaddress: string;
  siteid_guid: XQW.Guid;
  skills: string;
  stageid: XQW.Guid;
  systemuserid: XQW.Guid;
  territoryid_guid: XQW.Guid;
  timezoneruleversionnumber: number;
  title: string;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  userlicensetype: number;
  userpuid: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
  windowsliveid: string;
  yammeremailaddress: string;
  yammeruserid: string;
}
interface SystemUser_Expand {
  createdby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdby_connection: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { createdby_connection: Connection_Result[] }>;
  createdonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  lk_PostFollow_createdby: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { lk_PostFollow_createdby: PostFollow_Result[] }>;
  lk_connectionbase_createdonbehalfby: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { lk_connectionbase_createdonbehalfby: Connection_Result[] }>;
  lk_connectionbase_modifiedonbehalfby: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { lk_connectionbase_modifiedonbehalfby: Connection_Result[] }>;
  lk_hr_casesubtype_createdby: WebExpand<SystemUser_Expand, hr_CaseSubType_Select, hr_CaseSubType_Filter, { lk_hr_casesubtype_createdby: hr_CaseSubType_Result[] }>;
  lk_hr_casesubtype_createdonbehalfby: WebExpand<SystemUser_Expand, hr_CaseSubType_Select, hr_CaseSubType_Filter, { lk_hr_casesubtype_createdonbehalfby: hr_CaseSubType_Result[] }>;
  lk_hr_casesubtype_modifiedby: WebExpand<SystemUser_Expand, hr_CaseSubType_Select, hr_CaseSubType_Filter, { lk_hr_casesubtype_modifiedby: hr_CaseSubType_Result[] }>;
  lk_hr_casesubtype_modifiedonbehalfby: WebExpand<SystemUser_Expand, hr_CaseSubType_Select, hr_CaseSubType_Filter, { lk_hr_casesubtype_modifiedonbehalfby: hr_CaseSubType_Result[] }>;
  lk_hr_casetype_createdby: WebExpand<SystemUser_Expand, hr_CaseType_Select, hr_CaseType_Filter, { lk_hr_casetype_createdby: hr_CaseType_Result[] }>;
  lk_hr_casetype_createdonbehalfby: WebExpand<SystemUser_Expand, hr_CaseType_Select, hr_CaseType_Filter, { lk_hr_casetype_createdonbehalfby: hr_CaseType_Result[] }>;
  lk_hr_casetype_modifiedby: WebExpand<SystemUser_Expand, hr_CaseType_Select, hr_CaseType_Filter, { lk_hr_casetype_modifiedby: hr_CaseType_Result[] }>;
  lk_hr_casetype_modifiedonbehalfby: WebExpand<SystemUser_Expand, hr_CaseType_Select, hr_CaseType_Filter, { lk_hr_casetype_modifiedonbehalfby: hr_CaseType_Result[] }>;
  lk_hr_hrcase_createdby: WebExpand<SystemUser_Expand, hr_HRCase_Select, hr_HRCase_Filter, { lk_hr_hrcase_createdby: hr_HRCase_Result[] }>;
  lk_hr_hrcase_createdonbehalfby: WebExpand<SystemUser_Expand, hr_HRCase_Select, hr_HRCase_Filter, { lk_hr_hrcase_createdonbehalfby: hr_HRCase_Result[] }>;
  lk_hr_hrcase_modifiedby: WebExpand<SystemUser_Expand, hr_HRCase_Select, hr_HRCase_Filter, { lk_hr_hrcase_modifiedby: hr_HRCase_Result[] }>;
  lk_hr_hrcase_modifiedonbehalfby: WebExpand<SystemUser_Expand, hr_HRCase_Select, hr_HRCase_Filter, { lk_hr_hrcase_modifiedonbehalfby: hr_HRCase_Result[] }>;
  lk_hr_questionandanswers_createdby: WebExpand<SystemUser_Expand, hr_QuestionandAnswers_Select, hr_QuestionandAnswers_Filter, { lk_hr_questionandanswers_createdby: hr_QuestionandAnswers_Result[] }>;
  lk_hr_questionandanswers_createdonbehalfby: WebExpand<SystemUser_Expand, hr_QuestionandAnswers_Select, hr_QuestionandAnswers_Filter, { lk_hr_questionandanswers_createdonbehalfby: hr_QuestionandAnswers_Result[] }>;
  lk_hr_questionandanswers_modifiedby: WebExpand<SystemUser_Expand, hr_QuestionandAnswers_Select, hr_QuestionandAnswers_Filter, { lk_hr_questionandanswers_modifiedby: hr_QuestionandAnswers_Result[] }>;
  lk_hr_questionandanswers_modifiedonbehalfby: WebExpand<SystemUser_Expand, hr_QuestionandAnswers_Select, hr_QuestionandAnswers_Filter, { lk_hr_questionandanswers_modifiedonbehalfby: hr_QuestionandAnswers_Result[] }>;
  lk_post_createdby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_createdby: Post_Result[] }>;
  lk_post_createdonbehalfby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_createdonbehalfby: Post_Result[] }>;
  lk_post_modifiedby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_modifiedby: Post_Result[] }>;
  lk_post_modifiedonbehalfby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_modifiedonbehalfby: Post_Result[] }>;
  lk_postfollow_createdonbehalfby: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { lk_postfollow_createdonbehalfby: PostFollow_Result[] }>;
  lk_systemuser_createdonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuser_createdonbehalfby: SystemUser_Result[] }>;
  lk_systemuser_modifiedonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuser_modifiedonbehalfby: SystemUser_Result[] }>;
  lk_systemuserbase_createdby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuserbase_createdby: SystemUser_Result[] }>;
  lk_systemuserbase_modifiedby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuserbase_modifiedby: SystemUser_Result[] }>;
  lk_templatebase_createdby: WebExpand<SystemUser_Expand, Template_Select, Template_Filter, { lk_templatebase_createdby: Template_Result[] }>;
  lk_templatebase_createdonbehalfby: WebExpand<SystemUser_Expand, Template_Select, Template_Filter, { lk_templatebase_createdonbehalfby: Template_Result[] }>;
  lk_templatebase_modifiedby: WebExpand<SystemUser_Expand, Template_Select, Template_Filter, { lk_templatebase_modifiedby: Template_Result[] }>;
  lk_templatebase_modifiedonbehalfby: WebExpand<SystemUser_Expand, Template_Select, Template_Filter, { lk_templatebase_modifiedonbehalfby: Template_Result[] }>;
  modifiedby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedby_connection: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { modifiedby_connection: Connection_Result[] }>;
  modifiedonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  parentsystemuserid: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { parentsystemuserid: SystemUser_Result }>;
  system_user_email_templates: WebExpand<SystemUser_Expand, Template_Select, Template_Filter, { system_user_email_templates: Template_Result[] }>;
  systemuser_PostFollows: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { systemuser_PostFollows: PostFollow_Result[] }>;
  systemuser_connections1: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { systemuser_connections1: Connection_Result[] }>;
  systemuser_connections2: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { systemuser_connections2: Connection_Result[] }>;
  user_hr_casesubtype: WebExpand<SystemUser_Expand, hr_CaseSubType_Select, hr_CaseSubType_Filter, { user_hr_casesubtype: hr_CaseSubType_Result[] }>;
  user_hr_casetype: WebExpand<SystemUser_Expand, hr_CaseType_Select, hr_CaseType_Filter, { user_hr_casetype: hr_CaseType_Result[] }>;
  user_hr_hrcase: WebExpand<SystemUser_Expand, hr_HRCase_Select, hr_HRCase_Filter, { user_hr_hrcase: hr_HRCase_Result[] }>;
  user_hr_questionandanswers: WebExpand<SystemUser_Expand, hr_QuestionandAnswers_Select, hr_QuestionandAnswers_Filter, { user_hr_questionandanswers: hr_QuestionandAnswers_Result[] }>;
  user_owner_postfollows: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { user_owner_postfollows: PostFollow_Result[] }>;
  user_parent_user: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { user_parent_user: SystemUser_Result[] }>;
}
interface SystemUser_FormattedResult {
  accessmode_formatted?: string;
  address1_addresstypecode_formatted?: string;
  address1_shippingmethodcode_formatted?: string;
  address2_addresstypecode_formatted?: string;
  address2_shippingmethodcode_formatted?: string;
  businessunitid_formatted?: string;
  calendarid_formatted?: string;
  caltype_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  defaultmailbox_formatted?: string;
  emailrouteraccessapproval_formatted?: string;
  incomingemaildeliverymethod_formatted?: string;
  invitestatuscode_formatted?: string;
  latestupdatetime_formatted?: string;
  mobileofflineprofileid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  outgoingemaildeliverymethod_formatted?: string;
  overriddencreatedon_formatted?: string;
  parentsystemuserid_formatted?: string;
  positionid_formatted?: string;
  preferredaddresscode_formatted?: string;
  preferredemailcode_formatted?: string;
  preferredphonecode_formatted?: string;
  queueid_formatted?: string;
  siteid_formatted?: string;
  territoryid_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface SystemUser_Result extends SystemUser_Base, SystemUser_Relationships {
  "@odata.etag": string;
  businessunitid_guid: string | null;
  calendarid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  defaultmailbox_guid: string | null;
  mobileofflineprofileid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  parentsystemuserid_guid: string | null;
  positionid_guid: string | null;
  queueid_guid: string | null;
  siteid_guid: string | null;
  territoryid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface SystemUser_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentsystemuserid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface SystemUser_RelatedMany {
  createdby_connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  lk_PostFollow_createdby: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  lk_connectionbase_createdonbehalfby: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  lk_connectionbase_modifiedonbehalfby: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  lk_hr_casesubtype_createdby: WebMappingRetrieve<hr_CaseSubType_Select,hr_CaseSubType_Expand,hr_CaseSubType_Filter,hr_CaseSubType_Fixed,hr_CaseSubType_Result,hr_CaseSubType_FormattedResult>;
  lk_hr_casesubtype_createdonbehalfby: WebMappingRetrieve<hr_CaseSubType_Select,hr_CaseSubType_Expand,hr_CaseSubType_Filter,hr_CaseSubType_Fixed,hr_CaseSubType_Result,hr_CaseSubType_FormattedResult>;
  lk_hr_casesubtype_modifiedby: WebMappingRetrieve<hr_CaseSubType_Select,hr_CaseSubType_Expand,hr_CaseSubType_Filter,hr_CaseSubType_Fixed,hr_CaseSubType_Result,hr_CaseSubType_FormattedResult>;
  lk_hr_casesubtype_modifiedonbehalfby: WebMappingRetrieve<hr_CaseSubType_Select,hr_CaseSubType_Expand,hr_CaseSubType_Filter,hr_CaseSubType_Fixed,hr_CaseSubType_Result,hr_CaseSubType_FormattedResult>;
  lk_hr_casetype_createdby: WebMappingRetrieve<hr_CaseType_Select,hr_CaseType_Expand,hr_CaseType_Filter,hr_CaseType_Fixed,hr_CaseType_Result,hr_CaseType_FormattedResult>;
  lk_hr_casetype_createdonbehalfby: WebMappingRetrieve<hr_CaseType_Select,hr_CaseType_Expand,hr_CaseType_Filter,hr_CaseType_Fixed,hr_CaseType_Result,hr_CaseType_FormattedResult>;
  lk_hr_casetype_modifiedby: WebMappingRetrieve<hr_CaseType_Select,hr_CaseType_Expand,hr_CaseType_Filter,hr_CaseType_Fixed,hr_CaseType_Result,hr_CaseType_FormattedResult>;
  lk_hr_casetype_modifiedonbehalfby: WebMappingRetrieve<hr_CaseType_Select,hr_CaseType_Expand,hr_CaseType_Filter,hr_CaseType_Fixed,hr_CaseType_Result,hr_CaseType_FormattedResult>;
  lk_hr_hrcase_createdby: WebMappingRetrieve<hr_HRCase_Select,hr_HRCase_Expand,hr_HRCase_Filter,hr_HRCase_Fixed,hr_HRCase_Result,hr_HRCase_FormattedResult>;
  lk_hr_hrcase_createdonbehalfby: WebMappingRetrieve<hr_HRCase_Select,hr_HRCase_Expand,hr_HRCase_Filter,hr_HRCase_Fixed,hr_HRCase_Result,hr_HRCase_FormattedResult>;
  lk_hr_hrcase_modifiedby: WebMappingRetrieve<hr_HRCase_Select,hr_HRCase_Expand,hr_HRCase_Filter,hr_HRCase_Fixed,hr_HRCase_Result,hr_HRCase_FormattedResult>;
  lk_hr_hrcase_modifiedonbehalfby: WebMappingRetrieve<hr_HRCase_Select,hr_HRCase_Expand,hr_HRCase_Filter,hr_HRCase_Fixed,hr_HRCase_Result,hr_HRCase_FormattedResult>;
  lk_hr_questionandanswers_createdby: WebMappingRetrieve<hr_QuestionandAnswers_Select,hr_QuestionandAnswers_Expand,hr_QuestionandAnswers_Filter,hr_QuestionandAnswers_Fixed,hr_QuestionandAnswers_Result,hr_QuestionandAnswers_FormattedResult>;
  lk_hr_questionandanswers_createdonbehalfby: WebMappingRetrieve<hr_QuestionandAnswers_Select,hr_QuestionandAnswers_Expand,hr_QuestionandAnswers_Filter,hr_QuestionandAnswers_Fixed,hr_QuestionandAnswers_Result,hr_QuestionandAnswers_FormattedResult>;
  lk_hr_questionandanswers_modifiedby: WebMappingRetrieve<hr_QuestionandAnswers_Select,hr_QuestionandAnswers_Expand,hr_QuestionandAnswers_Filter,hr_QuestionandAnswers_Fixed,hr_QuestionandAnswers_Result,hr_QuestionandAnswers_FormattedResult>;
  lk_hr_questionandanswers_modifiedonbehalfby: WebMappingRetrieve<hr_QuestionandAnswers_Select,hr_QuestionandAnswers_Expand,hr_QuestionandAnswers_Filter,hr_QuestionandAnswers_Fixed,hr_QuestionandAnswers_Result,hr_QuestionandAnswers_FormattedResult>;
  lk_post_createdby: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  lk_post_createdonbehalfby: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  lk_post_modifiedby: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  lk_post_modifiedonbehalfby: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  lk_postfollow_createdonbehalfby: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  lk_systemuser_createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  lk_systemuser_modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  lk_systemuserbase_createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  lk_systemuserbase_modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  lk_templatebase_createdby: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  lk_templatebase_createdonbehalfby: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  lk_templatebase_modifiedby: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  lk_templatebase_modifiedonbehalfby: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  modifiedby_connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  system_user_email_templates: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  systemuser_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  systemuser_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  systemuser_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  user_hr_casesubtype: WebMappingRetrieve<hr_CaseSubType_Select,hr_CaseSubType_Expand,hr_CaseSubType_Filter,hr_CaseSubType_Fixed,hr_CaseSubType_Result,hr_CaseSubType_FormattedResult>;
  user_hr_casetype: WebMappingRetrieve<hr_CaseType_Select,hr_CaseType_Expand,hr_CaseType_Filter,hr_CaseType_Fixed,hr_CaseType_Result,hr_CaseType_FormattedResult>;
  user_hr_hrcase: WebMappingRetrieve<hr_HRCase_Select,hr_HRCase_Expand,hr_HRCase_Filter,hr_HRCase_Fixed,hr_HRCase_Result,hr_HRCase_FormattedResult>;
  user_hr_questionandanswers: WebMappingRetrieve<hr_QuestionandAnswers_Select,hr_QuestionandAnswers_Expand,hr_QuestionandAnswers_Filter,hr_QuestionandAnswers_Fixed,hr_QuestionandAnswers_Result,hr_QuestionandAnswers_FormattedResult>;
  user_owner_postfollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  user_parent_user: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface WebEntitiesRetrieve {
  systemusers: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface WebEntitiesRelated {
  systemusers: WebMappingRelated<SystemUser_RelatedOne,SystemUser_RelatedMany>;
}
interface WebEntitiesCUDA {
  systemusers: WebMappingCUDA<SystemUser_Create,SystemUser_Update,SystemUser_Select>;
}
