//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021-02-15 3:55:30 PM
namespace Microsoft.Dynamics.CRM
{
        /// <summary>
        /// There are no comments for appconfigSingle in the schema.
        /// </summary>
    public partial class appconfigSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<appconfig>
    {
        /// <summary>
        /// Initialize a new appconfigSingle object.
        /// </summary>
        public appconfigSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new appconfigSingle object.
        /// </summary>
        public appconfigSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new appconfigSingle object.
        /// </summary>
        public appconfigSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<appconfig> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for appmodule_appconfig in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.appmoduleSingle appmodule_appconfig
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appmodule_appconfig == null))
                {
                    this._appmodule_appconfig = new global::Microsoft.Dynamics.CRM.appmoduleSingle(this.Context, GetPath("appmodule_appconfig"));
                }
                return this._appmodule_appconfig;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.appmoduleSingle _appmodule_appconfig;
        /// <summary>
        /// There are no comments for appconfig_modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfig_modifiedby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_modifiedby == null))
                {
                    this._appconfig_modifiedby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfig_modifiedby"));
                }
                return this._appconfig_modifiedby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfig_modifiedby;
        /// <summary>
        /// There are no comments for appconfig_modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfig_modifiedonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_modifiedonbehalfby == null))
                {
                    this._appconfig_modifiedonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfig_modifiedonbehalfby"));
                }
                return this._appconfig_modifiedonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfig_modifiedonbehalfby;
        /// <summary>
        /// There are no comments for appconfig_navigationsetting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.navigationsetting> appconfig_navigationsetting
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_navigationsetting == null))
                {
                    this._appconfig_navigationsetting = Context.CreateQuery<global::Microsoft.Dynamics.CRM.navigationsetting>(GetPath("appconfig_navigationsetting"));
                }
                return this._appconfig_navigationsetting;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.navigationsetting> _appconfig_navigationsetting;
        /// <summary>
        /// There are no comments for appconfig_createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfig_createdonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_createdonbehalfby == null))
                {
                    this._appconfig_createdonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfig_createdonbehalfby"));
                }
                return this._appconfig_createdonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfig_createdonbehalfby;
        /// <summary>
        /// There are no comments for appconfig_appconfiginstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.appconfiginstance> appconfig_appconfiginstance
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_appconfiginstance == null))
                {
                    this._appconfig_appconfiginstance = Context.CreateQuery<global::Microsoft.Dynamics.CRM.appconfiginstance>(GetPath("appconfig_appconfiginstance"));
                }
                return this._appconfig_appconfiginstance;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.appconfiginstance> _appconfig_appconfiginstance;
        /// <summary>
        /// There are no comments for appconfig_createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfig_createdby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfig_createdby == null))
                {
                    this._appconfig_createdby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfig_createdby"));
                }
                return this._appconfig_createdby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfig_createdby;
        /// <summary>
        /// There are no comments for organization_appconfig in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organizationSingle organization_appconfig
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._organization_appconfig == null))
                {
                    this._organization_appconfig = new global::Microsoft.Dynamics.CRM.organizationSingle(this.Context, GetPath("organization_appconfig"));
                }
                return this._organization_appconfig;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organizationSingle _organization_appconfig;
    }
        /// <summary>
        /// There are no comments for appconfig in the schema.
        /// </summary>
    /// <KeyProperties>
    /// appconfigid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("appconfigid")]
    public partial class appconfig : crmbaseentity
    {
        /// <summary>
        /// Create a new appconfig object.
        /// </summary>
        /// <param name="appmodule_appconfig">Initial value of appmodule_appconfig.</param>
        /// <param name="appconfig_modifiedby">Initial value of appconfig_modifiedby.</param>
        /// <param name="appconfig_modifiedonbehalfby">Initial value of appconfig_modifiedonbehalfby.</param>
        /// <param name="appconfig_createdonbehalfby">Initial value of appconfig_createdonbehalfby.</param>
        /// <param name="appconfig_createdby">Initial value of appconfig_createdby.</param>
        /// <param name="organization_appconfig">Initial value of organization_appconfig.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static appconfig Createappconfig(global::Microsoft.Dynamics.CRM.appmodule appmodule_appconfig, 
                    global::Microsoft.Dynamics.CRM.systemuser appconfig_modifiedby, 
                    global::Microsoft.Dynamics.CRM.systemuser appconfig_modifiedonbehalfby, 
                    global::Microsoft.Dynamics.CRM.systemuser appconfig_createdonbehalfby, 
                    global::Microsoft.Dynamics.CRM.systemuser appconfig_createdby, 
                    global::Microsoft.Dynamics.CRM.organization organization_appconfig)
        {
            appconfig appconfig = new appconfig();
            if ((appmodule_appconfig == null))
            {
                throw new global::System.ArgumentNullException("appmodule_appconfig");
            }
            appconfig.appmodule_appconfig = appmodule_appconfig;
            if ((appconfig_modifiedby == null))
            {
                throw new global::System.ArgumentNullException("appconfig_modifiedby");
            }
            appconfig.appconfig_modifiedby = appconfig_modifiedby;
            if ((appconfig_modifiedonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("appconfig_modifiedonbehalfby");
            }
            appconfig.appconfig_modifiedonbehalfby = appconfig_modifiedonbehalfby;
            if ((appconfig_createdonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("appconfig_createdonbehalfby");
            }
            appconfig.appconfig_createdonbehalfby = appconfig_createdonbehalfby;
            if ((appconfig_createdby == null))
            {
                throw new global::System.ArgumentNullException("appconfig_createdby");
            }
            appconfig.appconfig_createdby = appconfig_createdby;
            if ((organization_appconfig == null))
            {
                throw new global::System.ArgumentNullException("organization_appconfig");
            }
            appconfig.organization_appconfig = organization_appconfig;
            return appconfig;
        }
        /// <summary>
        /// There are no comments for Property componentstate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> componentstate
        {
            get
            {
                return this._componentstate;
            }
            set
            {
                this.OncomponentstateChanging(value);
                this._componentstate = value;
                this.OncomponentstateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _componentstate;
        partial void OncomponentstateChanging(global::System.Nullable<int> value);
        partial void OncomponentstateChanged();
        /// <summary>
        /// There are no comments for Property solutionid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> solutionid
        {
            get
            {
                return this._solutionid;
            }
            set
            {
                this.OnsolutionidChanging(value);
                this._solutionid = value;
                this.OnsolutionidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _solutionid;
        partial void OnsolutionidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnsolutionidChanged();
        /// <summary>
        /// There are no comments for Property importsequencenumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> importsequencenumber
        {
            get
            {
                return this._importsequencenumber;
            }
            set
            {
                this.OnimportsequencenumberChanging(value);
                this._importsequencenumber = value;
                this.OnimportsequencenumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _importsequencenumber;
        partial void OnimportsequencenumberChanging(global::System.Nullable<int> value);
        partial void OnimportsequencenumberChanged();
        /// <summary>
        /// There are no comments for Property versionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<long> versionnumber
        {
            get
            {
                return this._versionnumber;
            }
            set
            {
                this.OnversionnumberChanging(value);
                this._versionnumber = value;
                this.OnversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _versionnumber;
        partial void OnversionnumberChanging(global::System.Nullable<long> value);
        partial void OnversionnumberChanged();
        /// <summary>
        /// There are no comments for Property ismanaged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> ismanaged
        {
            get
            {
                return this._ismanaged;
            }
            set
            {
                this.OnismanagedChanging(value);
                this._ismanaged = value;
                this.OnismanagedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ismanaged;
        partial void OnismanagedChanging(global::System.Nullable<bool> value);
        partial void OnismanagedChanged();
        /// <summary>
        /// There are no comments for Property appconfigimportxml in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string appconfigimportxml
        {
            get
            {
                return this._appconfigimportxml;
            }
            set
            {
                this.OnappconfigimportxmlChanging(value);
                this._appconfigimportxml = value;
                this.OnappconfigimportxmlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _appconfigimportxml;
        partial void OnappconfigimportxmlChanging(string value);
        partial void OnappconfigimportxmlChanged();
        /// <summary>
        /// There are no comments for Property _createdonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdonbehalfby_value
        {
            get
            {
                return this.__createdonbehalfby_value;
            }
            set
            {
                this.On_createdonbehalfby_valueChanging(value);
                this.__createdonbehalfby_value = value;
                this.On_createdonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdonbehalfby_value;
        partial void On_createdonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property modifiedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this.OnmodifiedonChanging(value);
                this._modifiedon = value;
                this.OnmodifiedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _modifiedon;
        partial void OnmodifiedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnmodifiedonChanged();
        /// <summary>
        /// There are no comments for Property createdon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this.OncreatedonChanging(value);
                this._createdon = value;
                this.OncreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _createdon;
        partial void OncreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedonChanged();
        /// <summary>
        /// There are no comments for Property _organizationid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _organizationid_value
        {
            get
            {
                return this.__organizationid_value;
            }
            set
            {
                this.On_organizationid_valueChanging(value);
                this.__organizationid_value = value;
                this.On_organizationid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __organizationid_value;
        partial void On_organizationid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_organizationid_valueChanged();
        /// <summary>
        /// There are no comments for Property overriddencreatedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overriddencreatedon
        {
            get
            {
                return this._overriddencreatedon;
            }
            set
            {
                this.OnoverriddencreatedonChanging(value);
                this._overriddencreatedon = value;
                this.OnoverriddencreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overriddencreatedon;
        partial void OnoverriddencreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverriddencreatedonChanged();
        /// <summary>
        /// There are no comments for Property _createdby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdby_value
        {
            get
            {
                return this.__createdby_value;
            }
            set
            {
                this.On_createdby_valueChanging(value);
                this.__createdby_value = value;
                this.On_createdby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdby_value;
        partial void On_createdby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdby_valueChanged();
        /// <summary>
        /// There are no comments for Property overwritetime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overwritetime
        {
            get
            {
                return this._overwritetime;
            }
            set
            {
                this.OnoverwritetimeChanging(value);
                this._overwritetime = value;
                this.OnoverwritetimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overwritetime;
        partial void OnoverwritetimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverwritetimeChanged();
        /// <summary>
        /// There are no comments for Property appconfigidunique in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> appconfigidunique
        {
            get
            {
                return this._appconfigidunique;
            }
            set
            {
                this.OnappconfigiduniqueChanging(value);
                this._appconfigidunique = value;
                this.OnappconfigiduniqueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _appconfigidunique;
        partial void OnappconfigiduniqueChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnappconfigiduniqueChanged();
        /// <summary>
        /// There are no comments for Property introducedversion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string introducedversion
        {
            get
            {
                return this._introducedversion;
            }
            set
            {
                this.OnintroducedversionChanging(value);
                this._introducedversion = value;
                this.OnintroducedversionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _introducedversion;
        partial void OnintroducedversionChanging(string value);
        partial void OnintroducedversionChanged();
        /// <summary>
        /// There are no comments for Property _modifiedby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedby_value
        {
            get
            {
                return this.__modifiedby_value;
            }
            set
            {
                this.On_modifiedby_valueChanging(value);
                this.__modifiedby_value = value;
                this.On_modifiedby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedby_value;
        partial void On_modifiedby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedby_valueChanged();
        /// <summary>
        /// There are no comments for Property _appmoduleid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _appmoduleid_value
        {
            get
            {
                return this.__appmoduleid_value;
            }
            set
            {
                this.On_appmoduleid_valueChanging(value);
                this.__appmoduleid_value = value;
                this.On_appmoduleid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __appmoduleid_value;
        partial void On_appmoduleid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_appmoduleid_valueChanged();
        /// <summary>
        /// There are no comments for Property appconfigid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> appconfigid
        {
            get
            {
                return this._appconfigid;
            }
            set
            {
                this.OnappconfigidChanging(value);
                this._appconfigid = value;
                this.OnappconfigidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _appconfigid;
        partial void OnappconfigidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnappconfigidChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property _modifiedonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedonbehalfby_value
        {
            get
            {
                return this.__modifiedonbehalfby_value;
            }
            set
            {
                this.On_modifiedonbehalfby_valueChanging(value);
                this.__modifiedonbehalfby_value = value;
                this.On_modifiedonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedonbehalfby_value;
        partial void On_modifiedonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property appmodule_appconfig in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.appmodule appmodule_appconfig
        {
            get
            {
                return this._appmodule_appconfig;
            }
            set
            {
                this.Onappmodule_appconfigChanging(value);
                this._appmodule_appconfig = value;
                this.Onappmodule_appconfigChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.appmodule _appmodule_appconfig;
        partial void Onappmodule_appconfigChanging(global::Microsoft.Dynamics.CRM.appmodule value);
        partial void Onappmodule_appconfigChanged();
        /// <summary>
        /// There are no comments for Property appconfig_modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfig_modifiedby
        {
            get
            {
                return this._appconfig_modifiedby;
            }
            set
            {
                this.Onappconfig_modifiedbyChanging(value);
                this._appconfig_modifiedby = value;
                this.Onappconfig_modifiedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfig_modifiedby;
        partial void Onappconfig_modifiedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfig_modifiedbyChanged();
        /// <summary>
        /// There are no comments for Property appconfig_modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfig_modifiedonbehalfby
        {
            get
            {
                return this._appconfig_modifiedonbehalfby;
            }
            set
            {
                this.Onappconfig_modifiedonbehalfbyChanging(value);
                this._appconfig_modifiedonbehalfby = value;
                this.Onappconfig_modifiedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfig_modifiedonbehalfby;
        partial void Onappconfig_modifiedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfig_modifiedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property appconfig_navigationsetting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.navigationsetting> appconfig_navigationsetting
        {
            get
            {
                return this._appconfig_navigationsetting;
            }
            set
            {
                this.Onappconfig_navigationsettingChanging(value);
                this._appconfig_navigationsetting = value;
                this.Onappconfig_navigationsettingChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.navigationsetting> _appconfig_navigationsetting = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.navigationsetting>();
        partial void Onappconfig_navigationsettingChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.navigationsetting> value);
        partial void Onappconfig_navigationsettingChanged();
        /// <summary>
        /// There are no comments for Property appconfig_createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfig_createdonbehalfby
        {
            get
            {
                return this._appconfig_createdonbehalfby;
            }
            set
            {
                this.Onappconfig_createdonbehalfbyChanging(value);
                this._appconfig_createdonbehalfby = value;
                this.Onappconfig_createdonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfig_createdonbehalfby;
        partial void Onappconfig_createdonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfig_createdonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property appconfig_appconfiginstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> appconfig_appconfiginstance
        {
            get
            {
                return this._appconfig_appconfiginstance;
            }
            set
            {
                this.Onappconfig_appconfiginstanceChanging(value);
                this._appconfig_appconfiginstance = value;
                this.Onappconfig_appconfiginstanceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> _appconfig_appconfiginstance = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance>();
        partial void Onappconfig_appconfiginstanceChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> value);
        partial void Onappconfig_appconfiginstanceChanged();
        /// <summary>
        /// There are no comments for Property appconfig_createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfig_createdby
        {
            get
            {
                return this._appconfig_createdby;
            }
            set
            {
                this.Onappconfig_createdbyChanging(value);
                this._appconfig_createdby = value;
                this.Onappconfig_createdbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfig_createdby;
        partial void Onappconfig_createdbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfig_createdbyChanged();
        /// <summary>
        /// There are no comments for Property organization_appconfig in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organization organization_appconfig
        {
            get
            {
                return this._organization_appconfig;
            }
            set
            {
                this.Onorganization_appconfigChanging(value);
                this._organization_appconfig = value;
                this.Onorganization_appconfigChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organization _organization_appconfig;
        partial void Onorganization_appconfigChanging(global::Microsoft.Dynamics.CRM.organization value);
        partial void Onorganization_appconfigChanged();
    }
}
