//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021-02-15 3:55:30 PM
namespace Microsoft.Dynamics.CRM
{
        /// <summary>
        /// There are no comments for appconfigmasterSingle in the schema.
        /// </summary>
    public partial class appconfigmasterSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<appconfigmaster>
    {
        /// <summary>
        /// Initialize a new appconfigmasterSingle object.
        /// </summary>
        public appconfigmasterSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new appconfigmasterSingle object.
        /// </summary>
        public appconfigmasterSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new appconfigmasterSingle object.
        /// </summary>
        public appconfigmasterSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<appconfigmaster> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for appconfigmaster_appconfiginstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.appconfiginstance> appconfigmaster_appconfiginstance
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfigmaster_appconfiginstance == null))
                {
                    this._appconfigmaster_appconfiginstance = Context.CreateQuery<global::Microsoft.Dynamics.CRM.appconfiginstance>(GetPath("appconfigmaster_appconfiginstance"));
                }
                return this._appconfigmaster_appconfiginstance;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.appconfiginstance> _appconfigmaster_appconfiginstance;
        /// <summary>
        /// There are no comments for appconfigmaster_createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfigmaster_createdonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfigmaster_createdonbehalfby == null))
                {
                    this._appconfigmaster_createdonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfigmaster_createdonbehalfby"));
                }
                return this._appconfigmaster_createdonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfigmaster_createdonbehalfby;
        /// <summary>
        /// There are no comments for appconfigmaster_createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfigmaster_createdby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfigmaster_createdby == null))
                {
                    this._appconfigmaster_createdby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfigmaster_createdby"));
                }
                return this._appconfigmaster_createdby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfigmaster_createdby;
        /// <summary>
        /// There are no comments for organization_appconfigmaster_appconfigmaster in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organizationSingle organization_appconfigmaster_appconfigmaster
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._organization_appconfigmaster_appconfigmaster == null))
                {
                    this._organization_appconfigmaster_appconfigmaster = new global::Microsoft.Dynamics.CRM.organizationSingle(this.Context, GetPath("organization_appconfigmaster_appconfigmaster"));
                }
                return this._organization_appconfigmaster_appconfigmaster;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organizationSingle _organization_appconfigmaster_appconfigmaster;
        /// <summary>
        /// There are no comments for appconfigmaster_modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfigmaster_modifiedonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfigmaster_modifiedonbehalfby == null))
                {
                    this._appconfigmaster_modifiedonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfigmaster_modifiedonbehalfby"));
                }
                return this._appconfigmaster_modifiedonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfigmaster_modifiedonbehalfby;
        /// <summary>
        /// There are no comments for appconfigmaster_modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle appconfigmaster_modifiedby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._appconfigmaster_modifiedby == null))
                {
                    this._appconfigmaster_modifiedby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("appconfigmaster_modifiedby"));
                }
                return this._appconfigmaster_modifiedby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _appconfigmaster_modifiedby;
    }
        /// <summary>
        /// There are no comments for appconfigmaster in the schema.
        /// </summary>
    /// <KeyProperties>
    /// appconfigmasterid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("appconfigmasterid")]
    public partial class appconfigmaster : crmbaseentity
    {
        /// <summary>
        /// Create a new appconfigmaster object.
        /// </summary>
        /// <param name="appconfigmaster_createdonbehalfby">Initial value of appconfigmaster_createdonbehalfby.</param>
        /// <param name="appconfigmaster_createdby">Initial value of appconfigmaster_createdby.</param>
        /// <param name="organization_appconfigmaster_appconfigmaster">Initial value of organization_appconfigmaster_appconfigmaster.</param>
        /// <param name="appconfigmaster_modifiedonbehalfby">Initial value of appconfigmaster_modifiedonbehalfby.</param>
        /// <param name="appconfigmaster_modifiedby">Initial value of appconfigmaster_modifiedby.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static appconfigmaster Createappconfigmaster(global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_createdonbehalfby, global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_createdby, global::Microsoft.Dynamics.CRM.organization organization_appconfigmaster_appconfigmaster, global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_modifiedonbehalfby, global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_modifiedby)
        {
            appconfigmaster appconfigmaster = new appconfigmaster();
            if ((appconfigmaster_createdonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("appconfigmaster_createdonbehalfby");
            }
            appconfigmaster.appconfigmaster_createdonbehalfby = appconfigmaster_createdonbehalfby;
            if ((appconfigmaster_createdby == null))
            {
                throw new global::System.ArgumentNullException("appconfigmaster_createdby");
            }
            appconfigmaster.appconfigmaster_createdby = appconfigmaster_createdby;
            if ((organization_appconfigmaster_appconfigmaster == null))
            {
                throw new global::System.ArgumentNullException("organization_appconfigmaster_appconfigmaster");
            }
            appconfigmaster.organization_appconfigmaster_appconfigmaster = organization_appconfigmaster_appconfigmaster;
            if ((appconfigmaster_modifiedonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("appconfigmaster_modifiedonbehalfby");
            }
            appconfigmaster.appconfigmaster_modifiedonbehalfby = appconfigmaster_modifiedonbehalfby;
            if ((appconfigmaster_modifiedby == null))
            {
                throw new global::System.ArgumentNullException("appconfigmaster_modifiedby");
            }
            appconfigmaster.appconfigmaster_modifiedby = appconfigmaster_modifiedby;
            return appconfigmaster;
        }
        /// <summary>
        /// There are no comments for Property _modifiedby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedby_value
        {
            get
            {
                return this.__modifiedby_value;
            }
            set
            {
                this.On_modifiedby_valueChanging(value);
                this.__modifiedby_value = value;
                this.On_modifiedby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedby_value;
        partial void On_modifiedby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedby_valueChanged();
        /// <summary>
        /// There are no comments for Property overriddencreatedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overriddencreatedon
        {
            get
            {
                return this._overriddencreatedon;
            }
            set
            {
                this.OnoverriddencreatedonChanging(value);
                this._overriddencreatedon = value;
                this.OnoverriddencreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overriddencreatedon;
        partial void OnoverriddencreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverriddencreatedonChanged();
        /// <summary>
        /// There are no comments for Property configtype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string configtype
        {
            get
            {
                return this._configtype;
            }
            set
            {
                this.OnconfigtypeChanging(value);
                this._configtype = value;
                this.OnconfigtypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _configtype;
        partial void OnconfigtypeChanging(string value);
        partial void OnconfigtypeChanged();
        /// <summary>
        /// There are no comments for Property modifiedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this.OnmodifiedonChanging(value);
                this._modifiedon = value;
                this.OnmodifiedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _modifiedon;
        partial void OnmodifiedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnmodifiedonChanged();
        /// <summary>
        /// There are no comments for Property _modifiedonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedonbehalfby_value
        {
            get
            {
                return this.__modifiedonbehalfby_value;
            }
            set
            {
                this.On_modifiedonbehalfby_valueChanging(value);
                this.__modifiedonbehalfby_value = value;
                this.On_modifiedonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedonbehalfby_value;
        partial void On_modifiedonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property defaultvalue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string defaultvalue
        {
            get
            {
                return this._defaultvalue;
            }
            set
            {
                this.OndefaultvalueChanging(value);
                this._defaultvalue = value;
                this.OndefaultvalueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _defaultvalue;
        partial void OndefaultvalueChanging(string value);
        partial void OndefaultvalueChanged();
        /// <summary>
        /// There are no comments for Property isnavigationsetting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> isnavigationsetting
        {
            get
            {
                return this._isnavigationsetting;
            }
            set
            {
                this.OnisnavigationsettingChanging(value);
                this._isnavigationsetting = value;
                this.OnisnavigationsettingChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _isnavigationsetting;
        partial void OnisnavigationsettingChanging(global::System.Nullable<int> value);
        partial void OnisnavigationsettingChanged();
        /// <summary>
        /// There are no comments for Property versionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<long> versionnumber
        {
            get
            {
                return this._versionnumber;
            }
            set
            {
                this.OnversionnumberChanging(value);
                this._versionnumber = value;
                this.OnversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _versionnumber;
        partial void OnversionnumberChanging(global::System.Nullable<long> value);
        partial void OnversionnumberChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property _createdonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdonbehalfby_value
        {
            get
            {
                return this.__createdonbehalfby_value;
            }
            set
            {
                this.On_createdonbehalfby_valueChanging(value);
                this.__createdonbehalfby_value = value;
                this.On_createdonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdonbehalfby_value;
        partial void On_createdonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property createdon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this.OncreatedonChanging(value);
                this._createdon = value;
                this.OncreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _createdon;
        partial void OncreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedonChanged();
        /// <summary>
        /// There are no comments for Property importsequencenumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> importsequencenumber
        {
            get
            {
                return this._importsequencenumber;
            }
            set
            {
                this.OnimportsequencenumberChanging(value);
                this._importsequencenumber = value;
                this.OnimportsequencenumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _importsequencenumber;
        partial void OnimportsequencenumberChanging(global::System.Nullable<int> value);
        partial void OnimportsequencenumberChanged();
        /// <summary>
        /// There are no comments for Property validator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string validator
        {
            get
            {
                return this._validator;
            }
            set
            {
                this.OnvalidatorChanging(value);
                this._validator = value;
                this.OnvalidatorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _validator;
        partial void OnvalidatorChanging(string value);
        partial void OnvalidatorChanged();
        /// <summary>
        /// There are no comments for Property _organizationid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _organizationid_value
        {
            get
            {
                return this.__organizationid_value;
            }
            set
            {
                this.On_organizationid_valueChanging(value);
                this.__organizationid_value = value;
                this.On_organizationid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __organizationid_value;
        partial void On_organizationid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_organizationid_valueChanged();
        /// <summary>
        /// There are no comments for Property parentappconfigmasterid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string parentappconfigmasterid
        {
            get
            {
                return this._parentappconfigmasterid;
            }
            set
            {
                this.OnparentappconfigmasteridChanging(value);
                this._parentappconfigmasterid = value;
                this.OnparentappconfigmasteridChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _parentappconfigmasterid;
        partial void OnparentappconfigmasteridChanging(string value);
        partial void OnparentappconfigmasteridChanged();
        /// <summary>
        /// There are no comments for Property appconfigmasterid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> appconfigmasterid
        {
            get
            {
                return this._appconfigmasterid;
            }
            set
            {
                this.OnappconfigmasteridChanging(value);
                this._appconfigmasterid = value;
                this.OnappconfigmasteridChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _appconfigmasterid;
        partial void OnappconfigmasteridChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnappconfigmasteridChanged();
        /// <summary>
        /// There are no comments for Property _createdby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdby_value
        {
            get
            {
                return this.__createdby_value;
            }
            set
            {
                this.On_createdby_valueChanging(value);
                this.__createdby_value = value;
                this.On_createdby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdby_value;
        partial void On_createdby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdby_valueChanged();
        /// <summary>
        /// There are no comments for Property appconfigmaster_appconfiginstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> appconfigmaster_appconfiginstance
        {
            get
            {
                return this._appconfigmaster_appconfiginstance;
            }
            set
            {
                this.Onappconfigmaster_appconfiginstanceChanging(value);
                this._appconfigmaster_appconfiginstance = value;
                this.Onappconfigmaster_appconfiginstanceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> _appconfigmaster_appconfiginstance = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance>();
        partial void Onappconfigmaster_appconfiginstanceChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.appconfiginstance> value);
        partial void Onappconfigmaster_appconfiginstanceChanged();
        /// <summary>
        /// There are no comments for Property appconfigmaster_createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_createdonbehalfby
        {
            get
            {
                return this._appconfigmaster_createdonbehalfby;
            }
            set
            {
                this.Onappconfigmaster_createdonbehalfbyChanging(value);
                this._appconfigmaster_createdonbehalfby = value;
                this.Onappconfigmaster_createdonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfigmaster_createdonbehalfby;
        partial void Onappconfigmaster_createdonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfigmaster_createdonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property appconfigmaster_createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_createdby
        {
            get
            {
                return this._appconfigmaster_createdby;
            }
            set
            {
                this.Onappconfigmaster_createdbyChanging(value);
                this._appconfigmaster_createdby = value;
                this.Onappconfigmaster_createdbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfigmaster_createdby;
        partial void Onappconfigmaster_createdbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfigmaster_createdbyChanged();
        /// <summary>
        /// There are no comments for Property organization_appconfigmaster_appconfigmaster in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organization organization_appconfigmaster_appconfigmaster
        {
            get
            {
                return this._organization_appconfigmaster_appconfigmaster;
            }
            set
            {
                this.Onorganization_appconfigmaster_appconfigmasterChanging(value);
                this._organization_appconfigmaster_appconfigmaster = value;
                this.Onorganization_appconfigmaster_appconfigmasterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organization _organization_appconfigmaster_appconfigmaster;
        partial void Onorganization_appconfigmaster_appconfigmasterChanging(global::Microsoft.Dynamics.CRM.organization value);
        partial void Onorganization_appconfigmaster_appconfigmasterChanged();
        /// <summary>
        /// There are no comments for Property appconfigmaster_modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_modifiedonbehalfby
        {
            get
            {
                return this._appconfigmaster_modifiedonbehalfby;
            }
            set
            {
                this.Onappconfigmaster_modifiedonbehalfbyChanging(value);
                this._appconfigmaster_modifiedonbehalfby = value;
                this.Onappconfigmaster_modifiedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfigmaster_modifiedonbehalfby;
        partial void Onappconfigmaster_modifiedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfigmaster_modifiedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property appconfigmaster_modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser appconfigmaster_modifiedby
        {
            get
            {
                return this._appconfigmaster_modifiedby;
            }
            set
            {
                this.Onappconfigmaster_modifiedbyChanging(value);
                this._appconfigmaster_modifiedby = value;
                this.Onappconfigmaster_modifiedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _appconfigmaster_modifiedby;
        partial void Onappconfigmaster_modifiedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void Onappconfigmaster_modifiedbyChanged();
    }
}
