//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021-02-15 3:55:30 PM
namespace Microsoft.Dynamics.CRM
{
        /// <summary>
        /// There are no comments for contracttemplateSingle in the schema.
        /// </summary>
    public partial class contracttemplateSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<contracttemplate>
    {
        /// <summary>
        /// Initialize a new contracttemplateSingle object.
        /// </summary>
        public contracttemplateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new contracttemplateSingle object.
        /// </summary>
        public contracttemplateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new contracttemplateSingle object.
        /// </summary>
        public contracttemplateSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<contracttemplate> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdby == null))
                {
                    this._createdby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdby"));
                }
                return this._createdby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdby;
        /// <summary>
        /// There are no comments for createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdonbehalfby == null))
                {
                    this._createdonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdonbehalfby"));
                }
                return this._createdonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdonbehalfby;
        /// <summary>
        /// There are no comments for modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedby == null))
                {
                    this._modifiedby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedby"));
                }
                return this._modifiedby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedby;
        /// <summary>
        /// There are no comments for modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedonbehalfby == null))
                {
                    this._modifiedonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedonbehalfby"));
                }
                return this._modifiedonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedonbehalfby;
        /// <summary>
        /// There are no comments for organizationid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organizationSingle organizationid
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._organizationid == null))
                {
                    this._organizationid = new global::Microsoft.Dynamics.CRM.organizationSingle(this.Context, GetPath("organizationid"));
                }
                return this._organizationid;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organizationSingle _organizationid;
        /// <summary>
        /// There are no comments for ContractTemplate_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> ContractTemplate_SyncErrors
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContractTemplate_SyncErrors == null))
                {
                    this._ContractTemplate_SyncErrors = Context.CreateQuery<global::Microsoft.Dynamics.CRM.syncerror>(GetPath("ContractTemplate_SyncErrors"));
                }
                return this._ContractTemplate_SyncErrors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> _ContractTemplate_SyncErrors;
        /// <summary>
        /// There are no comments for ContractTemplate_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> ContractTemplate_AsyncOperations
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContractTemplate_AsyncOperations == null))
                {
                    this._ContractTemplate_AsyncOperations = Context.CreateQuery<global::Microsoft.Dynamics.CRM.asyncoperation>(GetPath("ContractTemplate_AsyncOperations"));
                }
                return this._ContractTemplate_AsyncOperations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> _ContractTemplate_AsyncOperations;
        /// <summary>
        /// There are no comments for contracttemplate_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> contracttemplate_MailboxTrackingFolders
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._contracttemplate_MailboxTrackingFolders == null))
                {
                    this._contracttemplate_MailboxTrackingFolders = Context.CreateQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>(GetPath("contracttemplate_MailboxTrackingFolders"));
                }
                return this._contracttemplate_MailboxTrackingFolders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _contracttemplate_MailboxTrackingFolders;
        /// <summary>
        /// There are no comments for ContractTemplate_ProcessSessions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> ContractTemplate_ProcessSessions
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContractTemplate_ProcessSessions == null))
                {
                    this._ContractTemplate_ProcessSessions = Context.CreateQuery<global::Microsoft.Dynamics.CRM.processsession>(GetPath("ContractTemplate_ProcessSessions"));
                }
                return this._ContractTemplate_ProcessSessions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> _ContractTemplate_ProcessSessions;
        /// <summary>
        /// There are no comments for ContractTemplate_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> ContractTemplate_BulkDeleteFailures
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContractTemplate_BulkDeleteFailures == null))
                {
                    this._ContractTemplate_BulkDeleteFailures = Context.CreateQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure>(GetPath("ContractTemplate_BulkDeleteFailures"));
                }
                return this._ContractTemplate_BulkDeleteFailures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _ContractTemplate_BulkDeleteFailures;
        /// <summary>
        /// There are no comments for contracttemplate_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> contracttemplate_PrincipalObjectAttributeAccesses
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._contracttemplate_PrincipalObjectAttributeAccesses == null))
                {
                    this._contracttemplate_PrincipalObjectAttributeAccesses = Context.CreateQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>(GetPath("contracttemplate_PrincipalObjectAttributeAccesses"));
                }
                return this._contracttemplate_PrincipalObjectAttributeAccesses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _contracttemplate_PrincipalObjectAttributeAccesses;
        /// <summary>
        /// There are no comments for contract_template_contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.contract> contract_template_contracts
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._contract_template_contracts == null))
                {
                    this._contract_template_contracts = Context.CreateQuery<global::Microsoft.Dynamics.CRM.contract>(GetPath("contract_template_contracts"));
                }
                return this._contract_template_contracts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.contract> _contract_template_contracts;
    }
        /// <summary>
        /// There are no comments for contracttemplate in the schema.
        /// </summary>
    /// <KeyProperties>
    /// contracttemplateid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("contracttemplateid")]
    public partial class contracttemplate : crmbaseentity
    {
        /// <summary>
        /// Create a new contracttemplate object.
        /// </summary>
        /// <param name="createdby">Initial value of createdby.</param>
        /// <param name="createdonbehalfby">Initial value of createdonbehalfby.</param>
        /// <param name="modifiedby">Initial value of modifiedby.</param>
        /// <param name="modifiedonbehalfby">Initial value of modifiedonbehalfby.</param>
        /// <param name="organizationid">Initial value of organizationid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static contracttemplate Createcontracttemplate(global::Microsoft.Dynamics.CRM.systemuser createdby, global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby, global::Microsoft.Dynamics.CRM.systemuser modifiedby, global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby, global::Microsoft.Dynamics.CRM.organization organizationid)
        {
            contracttemplate contracttemplate = new contracttemplate();
            if ((createdby == null))
            {
                throw new global::System.ArgumentNullException("createdby");
            }
            contracttemplate.createdby = createdby;
            if ((createdonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("createdonbehalfby");
            }
            contracttemplate.createdonbehalfby = createdonbehalfby;
            if ((modifiedby == null))
            {
                throw new global::System.ArgumentNullException("modifiedby");
            }
            contracttemplate.modifiedby = modifiedby;
            if ((modifiedonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("modifiedonbehalfby");
            }
            contracttemplate.modifiedonbehalfby = modifiedonbehalfby;
            if ((organizationid == null))
            {
                throw new global::System.ArgumentNullException("organizationid");
            }
            contracttemplate.organizationid = organizationid;
            return contracttemplate;
        }
        /// <summary>
        /// There are no comments for Property effectivitycalendar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string effectivitycalendar
        {
            get
            {
                return this._effectivitycalendar;
            }
            set
            {
                this.OneffectivitycalendarChanging(value);
                this._effectivitycalendar = value;
                this.OneffectivitycalendarChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _effectivitycalendar;
        partial void OneffectivitycalendarChanging(string value);
        partial void OneffectivitycalendarChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property billingfrequencycode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> billingfrequencycode
        {
            get
            {
                return this._billingfrequencycode;
            }
            set
            {
                this.OnbillingfrequencycodeChanging(value);
                this._billingfrequencycode = value;
                this.OnbillingfrequencycodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _billingfrequencycode;
        partial void OnbillingfrequencycodeChanging(global::System.Nullable<int> value);
        partial void OnbillingfrequencycodeChanged();
        /// <summary>
        /// There are no comments for Property contractservicelevelcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> contractservicelevelcode
        {
            get
            {
                return this._contractservicelevelcode;
            }
            set
            {
                this.OncontractservicelevelcodeChanging(value);
                this._contractservicelevelcode = value;
                this.OncontractservicelevelcodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _contractservicelevelcode;
        partial void OncontractservicelevelcodeChanging(global::System.Nullable<int> value);
        partial void OncontractservicelevelcodeChanged();
        /// <summary>
        /// There are no comments for Property introducedversion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string introducedversion
        {
            get
            {
                return this._introducedversion;
            }
            set
            {
                this.OnintroducedversionChanging(value);
                this._introducedversion = value;
                this.OnintroducedversionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _introducedversion;
        partial void OnintroducedversionChanging(string value);
        partial void OnintroducedversionChanged();
        /// <summary>
        /// There are no comments for Property componentstate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> componentstate
        {
            get
            {
                return this._componentstate;
            }
            set
            {
                this.OncomponentstateChanging(value);
                this._componentstate = value;
                this.OncomponentstateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _componentstate;
        partial void OncomponentstateChanging(global::System.Nullable<int> value);
        partial void OncomponentstateChanged();
        /// <summary>
        /// There are no comments for Property _createdby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdby_value
        {
            get
            {
                return this.__createdby_value;
            }
            set
            {
                this.On_createdby_valueChanging(value);
                this.__createdby_value = value;
                this.On_createdby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdby_value;
        partial void On_createdby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdby_valueChanged();
        /// <summary>
        /// There are no comments for Property _organizationid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _organizationid_value
        {
            get
            {
                return this.__organizationid_value;
            }
            set
            {
                this.On_organizationid_valueChanging(value);
                this.__organizationid_value = value;
                this.On_organizationid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __organizationid_value;
        partial void On_organizationid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_organizationid_valueChanged();
        /// <summary>
        /// There are no comments for Property _modifiedonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedonbehalfby_value
        {
            get
            {
                return this.__modifiedonbehalfby_value;
            }
            set
            {
                this.On_modifiedonbehalfby_valueChanging(value);
                this.__modifiedonbehalfby_value = value;
                this.On_modifiedonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedonbehalfby_value;
        partial void On_modifiedonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property contracttemplateidunique in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> contracttemplateidunique
        {
            get
            {
                return this._contracttemplateidunique;
            }
            set
            {
                this.OncontracttemplateiduniqueChanging(value);
                this._contracttemplateidunique = value;
                this.OncontracttemplateiduniqueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _contracttemplateidunique;
        partial void OncontracttemplateiduniqueChanging(global::System.Nullable<global::System.Guid> value);
        partial void OncontracttemplateiduniqueChanged();
        /// <summary>
        /// There are no comments for Property _createdonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdonbehalfby_value
        {
            get
            {
                return this.__createdonbehalfby_value;
            }
            set
            {
                this.On_createdonbehalfby_valueChanging(value);
                this.__createdonbehalfby_value = value;
                this.On_createdonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdonbehalfby_value;
        partial void On_createdonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property _modifiedby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedby_value
        {
            get
            {
                return this.__modifiedby_value;
            }
            set
            {
                this.On_modifiedby_valueChanging(value);
                this.__modifiedby_value = value;
                this.On_modifiedby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedby_value;
        partial void On_modifiedby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedby_valueChanged();
        /// <summary>
        /// There are no comments for Property utcconversiontimezonecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> utcconversiontimezonecode
        {
            get
            {
                return this._utcconversiontimezonecode;
            }
            set
            {
                this.OnutcconversiontimezonecodeChanging(value);
                this._utcconversiontimezonecode = value;
                this.OnutcconversiontimezonecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _utcconversiontimezonecode;
        partial void OnutcconversiontimezonecodeChanging(global::System.Nullable<int> value);
        partial void OnutcconversiontimezonecodeChanged();
        /// <summary>
        /// There are no comments for Property contracttemplateid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> contracttemplateid
        {
            get
            {
                return this._contracttemplateid;
            }
            set
            {
                this.OncontracttemplateidChanging(value);
                this._contracttemplateid = value;
                this.OncontracttemplateidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _contracttemplateid;
        partial void OncontracttemplateidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OncontracttemplateidChanged();
        /// <summary>
        /// There are no comments for Property importsequencenumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> importsequencenumber
        {
            get
            {
                return this._importsequencenumber;
            }
            set
            {
                this.OnimportsequencenumberChanging(value);
                this._importsequencenumber = value;
                this.OnimportsequencenumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _importsequencenumber;
        partial void OnimportsequencenumberChanging(global::System.Nullable<int> value);
        partial void OnimportsequencenumberChanged();
        /// <summary>
        /// There are no comments for Property overwritetime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overwritetime
        {
            get
            {
                return this._overwritetime;
            }
            set
            {
                this.OnoverwritetimeChanging(value);
                this._overwritetime = value;
                this.OnoverwritetimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overwritetime;
        partial void OnoverwritetimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverwritetimeChanged();
        /// <summary>
        /// There are no comments for Property ismanaged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> ismanaged
        {
            get
            {
                return this._ismanaged;
            }
            set
            {
                this.OnismanagedChanging(value);
                this._ismanaged = value;
                this.OnismanagedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ismanaged;
        partial void OnismanagedChanging(global::System.Nullable<bool> value);
        partial void OnismanagedChanged();
        /// <summary>
        /// There are no comments for Property usediscountaspercentage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> usediscountaspercentage
        {
            get
            {
                return this._usediscountaspercentage;
            }
            set
            {
                this.OnusediscountaspercentageChanging(value);
                this._usediscountaspercentage = value;
                this.OnusediscountaspercentageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _usediscountaspercentage;
        partial void OnusediscountaspercentageChanging(global::System.Nullable<bool> value);
        partial void OnusediscountaspercentageChanged();
        /// <summary>
        /// There are no comments for Property iscustomizable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.BooleanManagedProperty iscustomizable
        {
            get
            {
                return this._iscustomizable;
            }
            set
            {
                this.OniscustomizableChanging(value);
                this._iscustomizable = value;
                this.OniscustomizableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.BooleanManagedProperty _iscustomizable;
        partial void OniscustomizableChanging(global::Microsoft.Dynamics.CRM.BooleanManagedProperty value);
        partial void OniscustomizableChanged();
        /// <summary>
        /// There are no comments for Property solutionid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> solutionid
        {
            get
            {
                return this._solutionid;
            }
            set
            {
                this.OnsolutionidChanging(value);
                this._solutionid = value;
                this.OnsolutionidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _solutionid;
        partial void OnsolutionidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnsolutionidChanged();
        /// <summary>
        /// There are no comments for Property abbreviation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string abbreviation
        {
            get
            {
                return this._abbreviation;
            }
            set
            {
                this.OnabbreviationChanging(value);
                this._abbreviation = value;
                this.OnabbreviationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _abbreviation;
        partial void OnabbreviationChanging(string value);
        partial void OnabbreviationChanged();
        /// <summary>
        /// There are no comments for Property createdon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this.OncreatedonChanging(value);
                this._createdon = value;
                this.OncreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _createdon;
        partial void OncreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedonChanged();
        /// <summary>
        /// There are no comments for Property versionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<long> versionnumber
        {
            get
            {
                return this._versionnumber;
            }
            set
            {
                this.OnversionnumberChanging(value);
                this._versionnumber = value;
                this.OnversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _versionnumber;
        partial void OnversionnumberChanging(global::System.Nullable<long> value);
        partial void OnversionnumberChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property allotmenttypecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> allotmenttypecode
        {
            get
            {
                return this._allotmenttypecode;
            }
            set
            {
                this.OnallotmenttypecodeChanging(value);
                this._allotmenttypecode = value;
                this.OnallotmenttypecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _allotmenttypecode;
        partial void OnallotmenttypecodeChanging(global::System.Nullable<int> value);
        partial void OnallotmenttypecodeChanged();
        /// <summary>
        /// There are no comments for Property modifiedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this.OnmodifiedonChanging(value);
                this._modifiedon = value;
                this.OnmodifiedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _modifiedon;
        partial void OnmodifiedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnmodifiedonChanged();
        /// <summary>
        /// There are no comments for Property timezoneruleversionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> timezoneruleversionnumber
        {
            get
            {
                return this._timezoneruleversionnumber;
            }
            set
            {
                this.OntimezoneruleversionnumberChanging(value);
                this._timezoneruleversionnumber = value;
                this.OntimezoneruleversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _timezoneruleversionnumber;
        partial void OntimezoneruleversionnumberChanging(global::System.Nullable<int> value);
        partial void OntimezoneruleversionnumberChanged();
        /// <summary>
        /// There are no comments for Property overriddencreatedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overriddencreatedon
        {
            get
            {
                return this._overriddencreatedon;
            }
            set
            {
                this.OnoverriddencreatedonChanging(value);
                this._overriddencreatedon = value;
                this.OnoverriddencreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overriddencreatedon;
        partial void OnoverriddencreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverriddencreatedonChanged();
        /// <summary>
        /// There are no comments for Property createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdby
        {
            get
            {
                return this._createdby;
            }
            set
            {
                this.OncreatedbyChanging(value);
                this._createdby = value;
                this.OncreatedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdby;
        partial void OncreatedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedbyChanged();
        /// <summary>
        /// There are no comments for Property createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby
        {
            get
            {
                return this._createdonbehalfby;
            }
            set
            {
                this.OncreatedonbehalfbyChanging(value);
                this._createdonbehalfby = value;
                this.OncreatedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdonbehalfby;
        partial void OncreatedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedby
        {
            get
            {
                return this._modifiedby;
            }
            set
            {
                this.OnmodifiedbyChanging(value);
                this._modifiedby = value;
                this.OnmodifiedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedby;
        partial void OnmodifiedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby
        {
            get
            {
                return this._modifiedonbehalfby;
            }
            set
            {
                this.OnmodifiedonbehalfbyChanging(value);
                this._modifiedonbehalfby = value;
                this.OnmodifiedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedonbehalfby;
        partial void OnmodifiedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property organizationid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organization organizationid
        {
            get
            {
                return this._organizationid;
            }
            set
            {
                this.OnorganizationidChanging(value);
                this._organizationid = value;
                this.OnorganizationidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organization _organizationid;
        partial void OnorganizationidChanging(global::Microsoft.Dynamics.CRM.organization value);
        partial void OnorganizationidChanged();
        /// <summary>
        /// There are no comments for Property ContractTemplate_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> ContractTemplate_SyncErrors
        {
            get
            {
                return this._ContractTemplate_SyncErrors;
            }
            set
            {
                this.OnContractTemplate_SyncErrorsChanging(value);
                this._ContractTemplate_SyncErrors = value;
                this.OnContractTemplate_SyncErrorsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> _ContractTemplate_SyncErrors = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror>();
        partial void OnContractTemplate_SyncErrorsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> value);
        partial void OnContractTemplate_SyncErrorsChanged();
        /// <summary>
        /// There are no comments for Property ContractTemplate_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> ContractTemplate_AsyncOperations
        {
            get
            {
                return this._ContractTemplate_AsyncOperations;
            }
            set
            {
                this.OnContractTemplate_AsyncOperationsChanging(value);
                this._ContractTemplate_AsyncOperations = value;
                this.OnContractTemplate_AsyncOperationsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> _ContractTemplate_AsyncOperations = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation>();
        partial void OnContractTemplate_AsyncOperationsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> value);
        partial void OnContractTemplate_AsyncOperationsChanged();
        /// <summary>
        /// There are no comments for Property contracttemplate_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> contracttemplate_MailboxTrackingFolders
        {
            get
            {
                return this._contracttemplate_MailboxTrackingFolders;
            }
            set
            {
                this.Oncontracttemplate_MailboxTrackingFoldersChanging(value);
                this._contracttemplate_MailboxTrackingFolders = value;
                this.Oncontracttemplate_MailboxTrackingFoldersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _contracttemplate_MailboxTrackingFolders = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>();
        partial void Oncontracttemplate_MailboxTrackingFoldersChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> value);
        partial void Oncontracttemplate_MailboxTrackingFoldersChanged();
        /// <summary>
        /// There are no comments for Property ContractTemplate_ProcessSessions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> ContractTemplate_ProcessSessions
        {
            get
            {
                return this._ContractTemplate_ProcessSessions;
            }
            set
            {
                this.OnContractTemplate_ProcessSessionsChanging(value);
                this._ContractTemplate_ProcessSessions = value;
                this.OnContractTemplate_ProcessSessionsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> _ContractTemplate_ProcessSessions = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession>();
        partial void OnContractTemplate_ProcessSessionsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> value);
        partial void OnContractTemplate_ProcessSessionsChanged();
        /// <summary>
        /// There are no comments for Property ContractTemplate_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> ContractTemplate_BulkDeleteFailures
        {
            get
            {
                return this._ContractTemplate_BulkDeleteFailures;
            }
            set
            {
                this.OnContractTemplate_BulkDeleteFailuresChanging(value);
                this._ContractTemplate_BulkDeleteFailures = value;
                this.OnContractTemplate_BulkDeleteFailuresChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _ContractTemplate_BulkDeleteFailures = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure>();
        partial void OnContractTemplate_BulkDeleteFailuresChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> value);
        partial void OnContractTemplate_BulkDeleteFailuresChanged();
        /// <summary>
        /// There are no comments for Property contracttemplate_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> contracttemplate_PrincipalObjectAttributeAccesses
        {
            get
            {
                return this._contracttemplate_PrincipalObjectAttributeAccesses;
            }
            set
            {
                this.Oncontracttemplate_PrincipalObjectAttributeAccessesChanging(value);
                this._contracttemplate_PrincipalObjectAttributeAccesses = value;
                this.Oncontracttemplate_PrincipalObjectAttributeAccessesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _contracttemplate_PrincipalObjectAttributeAccesses = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>();
        partial void Oncontracttemplate_PrincipalObjectAttributeAccessesChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> value);
        partial void Oncontracttemplate_PrincipalObjectAttributeAccessesChanged();
        /// <summary>
        /// There are no comments for Property contract_template_contracts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.contract> contract_template_contracts
        {
            get
            {
                return this._contract_template_contracts;
            }
            set
            {
                this.Oncontract_template_contractsChanging(value);
                this._contract_template_contracts = value;
                this.Oncontract_template_contractsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.contract> _contract_template_contracts = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.contract>();
        partial void Oncontract_template_contractsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.contract> value);
        partial void Oncontract_template_contractsChanged();
    }
}
