//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021-02-15 3:55:30 PM
namespace Microsoft.Dynamics.CRM
{
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfigurationSingle in the schema.
        /// </summary>
    public partial class msdyn_adaptivecardconfigurationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<msdyn_adaptivecardconfiguration>
    {
        /// <summary>
        /// Initialize a new msdyn_adaptivecardconfigurationSingle object.
        /// </summary>
        public msdyn_adaptivecardconfigurationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new msdyn_adaptivecardconfigurationSingle object.
        /// </summary>
        public msdyn_adaptivecardconfigurationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new msdyn_adaptivecardconfigurationSingle object.
        /// </summary>
        public msdyn_adaptivecardconfigurationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<msdyn_adaptivecardconfiguration> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdby == null))
                {
                    this._createdby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdby"));
                }
                return this._createdby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdby;
        /// <summary>
        /// There are no comments for createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdonbehalfby == null))
                {
                    this._createdonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdonbehalfby"));
                }
                return this._createdonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdonbehalfby;
        /// <summary>
        /// There are no comments for modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedby == null))
                {
                    this._modifiedby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedby"));
                }
                return this._modifiedby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedby;
        /// <summary>
        /// There are no comments for modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedonbehalfby == null))
                {
                    this._modifiedonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedonbehalfby"));
                }
                return this._modifiedonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedonbehalfby;
        /// <summary>
        /// There are no comments for organizationid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organizationSingle organizationid
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._organizationid == null))
                {
                    this._organizationid = new global::Microsoft.Dynamics.CRM.organizationSingle(this.Context, GetPath("organizationid"));
                }
                return this._organizationid;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organizationSingle _organizationid;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> msdyn_adaptivecardconfiguration_SyncErrors
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_SyncErrors == null))
                {
                    this._msdyn_adaptivecardconfiguration_SyncErrors = Context.CreateQuery<global::Microsoft.Dynamics.CRM.syncerror>(GetPath("msdyn_adaptivecardconfiguration_SyncErrors"));
                }
                return this._msdyn_adaptivecardconfiguration_SyncErrors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> _msdyn_adaptivecardconfiguration_SyncErrors;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> msdyn_adaptivecardconfiguration_AsyncOperations
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_AsyncOperations == null))
                {
                    this._msdyn_adaptivecardconfiguration_AsyncOperations = Context.CreateQuery<global::Microsoft.Dynamics.CRM.asyncoperation>(GetPath("msdyn_adaptivecardconfiguration_AsyncOperations"));
                }
                return this._msdyn_adaptivecardconfiguration_AsyncOperations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> _msdyn_adaptivecardconfiguration_AsyncOperations;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> msdyn_adaptivecardconfiguration_MailboxTrackingFolders
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_MailboxTrackingFolders == null))
                {
                    this._msdyn_adaptivecardconfiguration_MailboxTrackingFolders = Context.CreateQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>(GetPath("msdyn_adaptivecardconfiguration_MailboxTrackingFolders"));
                }
                return this._msdyn_adaptivecardconfiguration_MailboxTrackingFolders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _msdyn_adaptivecardconfiguration_MailboxTrackingFolders;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_ProcessSession in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> msdyn_adaptivecardconfiguration_ProcessSession
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_ProcessSession == null))
                {
                    this._msdyn_adaptivecardconfiguration_ProcessSession = Context.CreateQuery<global::Microsoft.Dynamics.CRM.processsession>(GetPath("msdyn_adaptivecardconfiguration_ProcessSession"));
                }
                return this._msdyn_adaptivecardconfiguration_ProcessSession;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> _msdyn_adaptivecardconfiguration_ProcessSession;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> msdyn_adaptivecardconfiguration_BulkDeleteFailures
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_BulkDeleteFailures == null))
                {
                    this._msdyn_adaptivecardconfiguration_BulkDeleteFailures = Context.CreateQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure>(GetPath("msdyn_adaptivecardconfiguration_BulkDeleteFailures"));
                }
                return this._msdyn_adaptivecardconfiguration_BulkDeleteFailures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _msdyn_adaptivecardconfiguration_BulkDeleteFailures;
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses == null))
                {
                    this._msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses = Context.CreateQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>(GetPath("msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses"));
                }
                return this._msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses;
    }
        /// <summary>
        /// There are no comments for msdyn_adaptivecardconfiguration in the schema.
        /// </summary>
    /// <KeyProperties>
    /// msdyn_adaptivecardconfigurationid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("msdyn_adaptivecardconfigurationid")]
    public partial class msdyn_adaptivecardconfiguration : crmbaseentity
    {
        /// <summary>
        /// Create a new msdyn_adaptivecardconfiguration object.
        /// </summary>
        /// <param name="createdby">Initial value of createdby.</param>
        /// <param name="createdonbehalfby">Initial value of createdonbehalfby.</param>
        /// <param name="modifiedby">Initial value of modifiedby.</param>
        /// <param name="modifiedonbehalfby">Initial value of modifiedonbehalfby.</param>
        /// <param name="organizationid">Initial value of organizationid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static msdyn_adaptivecardconfiguration Createmsdyn_adaptivecardconfiguration(global::Microsoft.Dynamics.CRM.systemuser createdby, global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby, global::Microsoft.Dynamics.CRM.systemuser modifiedby, global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby, global::Microsoft.Dynamics.CRM.organization organizationid)
        {
            msdyn_adaptivecardconfiguration msdyn_adaptivecardconfiguration = new msdyn_adaptivecardconfiguration();
            if ((createdby == null))
            {
                throw new global::System.ArgumentNullException("createdby");
            }
            msdyn_adaptivecardconfiguration.createdby = createdby;
            if ((createdonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("createdonbehalfby");
            }
            msdyn_adaptivecardconfiguration.createdonbehalfby = createdonbehalfby;
            if ((modifiedby == null))
            {
                throw new global::System.ArgumentNullException("modifiedby");
            }
            msdyn_adaptivecardconfiguration.modifiedby = modifiedby;
            if ((modifiedonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("modifiedonbehalfby");
            }
            msdyn_adaptivecardconfiguration.modifiedonbehalfby = modifiedonbehalfby;
            if ((organizationid == null))
            {
                throw new global::System.ArgumentNullException("organizationid");
            }
            msdyn_adaptivecardconfiguration.organizationid = organizationid;
            return msdyn_adaptivecardconfiguration;
        }
        /// <summary>
        /// There are no comments for Property importsequencenumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> importsequencenumber
        {
            get
            {
                return this._importsequencenumber;
            }
            set
            {
                this.OnimportsequencenumberChanging(value);
                this._importsequencenumber = value;
                this.OnimportsequencenumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _importsequencenumber;
        partial void OnimportsequencenumberChanging(global::System.Nullable<int> value);
        partial void OnimportsequencenumberChanged();
        /// <summary>
        /// There are no comments for Property componentstate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> componentstate
        {
            get
            {
                return this._componentstate;
            }
            set
            {
                this.OncomponentstateChanging(value);
                this._componentstate = value;
                this.OncomponentstateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _componentstate;
        partial void OncomponentstateChanging(global::System.Nullable<int> value);
        partial void OncomponentstateChanged();
        /// <summary>
        /// There are no comments for Property _organizationid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _organizationid_value
        {
            get
            {
                return this.__organizationid_value;
            }
            set
            {
                this.On_organizationid_valueChanging(value);
                this.__organizationid_value = value;
                this.On_organizationid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __organizationid_value;
        partial void On_organizationid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_organizationid_valueChanged();
        /// <summary>
        /// There are no comments for Property overwritetime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overwritetime
        {
            get
            {
                return this._overwritetime;
            }
            set
            {
                this.OnoverwritetimeChanging(value);
                this._overwritetime = value;
                this.OnoverwritetimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overwritetime;
        partial void OnoverwritetimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverwritetimeChanged();
        /// <summary>
        /// There are no comments for Property solutionid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> solutionid
        {
            get
            {
                return this._solutionid;
            }
            set
            {
                this.OnsolutionidChanging(value);
                this._solutionid = value;
                this.OnsolutionidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _solutionid;
        partial void OnsolutionidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnsolutionidChanged();
        /// <summary>
        /// There are no comments for Property _modifiedby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedby_value
        {
            get
            {
                return this.__modifiedby_value;
            }
            set
            {
                this.On_modifiedby_valueChanging(value);
                this.__modifiedby_value = value;
                this.On_modifiedby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedby_value;
        partial void On_modifiedby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedby_valueChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property msdyn_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_name
        {
            get
            {
                return this._msdyn_name;
            }
            set
            {
                this.Onmsdyn_nameChanging(value);
                this._msdyn_name = value;
                this.Onmsdyn_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_name;
        partial void Onmsdyn_nameChanging(string value);
        partial void Onmsdyn_nameChanged();
        /// <summary>
        /// There are no comments for Property componentidunique in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> componentidunique
        {
            get
            {
                return this._componentidunique;
            }
            set
            {
                this.OncomponentiduniqueChanging(value);
                this._componentidunique = value;
                this.OncomponentiduniqueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _componentidunique;
        partial void OncomponentiduniqueChanging(global::System.Nullable<global::System.Guid> value);
        partial void OncomponentiduniqueChanged();
        /// <summary>
        /// There are no comments for Property overriddencreatedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overriddencreatedon
        {
            get
            {
                return this._overriddencreatedon;
            }
            set
            {
                this.OnoverriddencreatedonChanging(value);
                this._overriddencreatedon = value;
                this.OnoverriddencreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overriddencreatedon;
        partial void OnoverriddencreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverriddencreatedonChanged();
        /// <summary>
        /// There are no comments for Property iscustomizable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.BooleanManagedProperty iscustomizable
        {
            get
            {
                return this._iscustomizable;
            }
            set
            {
                this.OniscustomizableChanging(value);
                this._iscustomizable = value;
                this.OniscustomizableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.BooleanManagedProperty _iscustomizable;
        partial void OniscustomizableChanging(global::Microsoft.Dynamics.CRM.BooleanManagedProperty value);
        partial void OniscustomizableChanged();
        /// <summary>
        /// There are no comments for Property _createdonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdonbehalfby_value
        {
            get
            {
                return this.__createdonbehalfby_value;
            }
            set
            {
                this.On_createdonbehalfby_valueChanging(value);
                this.__createdonbehalfby_value = value;
                this.On_createdonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdonbehalfby_value;
        partial void On_createdonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_uniquename in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_uniquename
        {
            get
            {
                return this._msdyn_uniquename;
            }
            set
            {
                this.Onmsdyn_uniquenameChanging(value);
                this._msdyn_uniquename = value;
                this.Onmsdyn_uniquenameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_uniquename;
        partial void Onmsdyn_uniquenameChanging(string value);
        partial void Onmsdyn_uniquenameChanged();
        /// <summary>
        /// There are no comments for Property modifiedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this.OnmodifiedonChanging(value);
                this._modifiedon = value;
                this.OnmodifiedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _modifiedon;
        partial void OnmodifiedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnmodifiedonChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property _createdby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdby_value
        {
            get
            {
                return this.__createdby_value;
            }
            set
            {
                this.On_createdby_valueChanging(value);
                this.__createdby_value = value;
                this.On_createdby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdby_value;
        partial void On_createdby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdby_valueChanged();
        /// <summary>
        /// There are no comments for Property ismanaged in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> ismanaged
        {
            get
            {
                return this._ismanaged;
            }
            set
            {
                this.OnismanagedChanging(value);
                this._ismanaged = value;
                this.OnismanagedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _ismanaged;
        partial void OnismanagedChanging(global::System.Nullable<bool> value);
        partial void OnismanagedChanged();
        /// <summary>
        /// There are no comments for Property timezoneruleversionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> timezoneruleversionnumber
        {
            get
            {
                return this._timezoneruleversionnumber;
            }
            set
            {
                this.OntimezoneruleversionnumberChanging(value);
                this._timezoneruleversionnumber = value;
                this.OntimezoneruleversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _timezoneruleversionnumber;
        partial void OntimezoneruleversionnumberChanging(global::System.Nullable<int> value);
        partial void OntimezoneruleversionnumberChanged();
        /// <summary>
        /// There are no comments for Property _modifiedonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedonbehalfby_value
        {
            get
            {
                return this.__modifiedonbehalfby_value;
            }
            set
            {
                this.On_modifiedonbehalfby_valueChanging(value);
                this.__modifiedonbehalfby_value = value;
                this.On_modifiedonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedonbehalfby_value;
        partial void On_modifiedonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property utcconversiontimezonecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> utcconversiontimezonecode
        {
            get
            {
                return this._utcconversiontimezonecode;
            }
            set
            {
                this.OnutcconversiontimezonecodeChanging(value);
                this._utcconversiontimezonecode = value;
                this.OnutcconversiontimezonecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _utcconversiontimezonecode;
        partial void OnutcconversiontimezonecodeChanging(global::System.Nullable<int> value);
        partial void OnutcconversiontimezonecodeChanged();
        /// <summary>
        /// There are no comments for Property versionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<long> versionnumber
        {
            get
            {
                return this._versionnumber;
            }
            set
            {
                this.OnversionnumberChanging(value);
                this._versionnumber = value;
                this.OnversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _versionnumber;
        partial void OnversionnumberChanging(global::System.Nullable<long> value);
        partial void OnversionnumberChanged();
        /// <summary>
        /// There are no comments for Property createdon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this.OncreatedonChanging(value);
                this._createdon = value;
                this.OncreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _createdon;
        partial void OncreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedonChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfigurationid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> msdyn_adaptivecardconfigurationid
        {
            get
            {
                return this._msdyn_adaptivecardconfigurationid;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfigurationidChanging(value);
                this._msdyn_adaptivecardconfigurationid = value;
                this.Onmsdyn_adaptivecardconfigurationidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _msdyn_adaptivecardconfigurationid;
        partial void Onmsdyn_adaptivecardconfigurationidChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onmsdyn_adaptivecardconfigurationidChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardtemplate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_adaptivecardtemplate
        {
            get
            {
                return this._msdyn_adaptivecardtemplate;
            }
            set
            {
                this.Onmsdyn_adaptivecardtemplateChanging(value);
                this._msdyn_adaptivecardtemplate = value;
                this.Onmsdyn_adaptivecardtemplateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_adaptivecardtemplate;
        partial void Onmsdyn_adaptivecardtemplateChanging(string value);
        partial void Onmsdyn_adaptivecardtemplateChanged();
        /// <summary>
        /// There are no comments for Property createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdby
        {
            get
            {
                return this._createdby;
            }
            set
            {
                this.OncreatedbyChanging(value);
                this._createdby = value;
                this.OncreatedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdby;
        partial void OncreatedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedbyChanged();
        /// <summary>
        /// There are no comments for Property createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby
        {
            get
            {
                return this._createdonbehalfby;
            }
            set
            {
                this.OncreatedonbehalfbyChanging(value);
                this._createdonbehalfby = value;
                this.OncreatedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdonbehalfby;
        partial void OncreatedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedby
        {
            get
            {
                return this._modifiedby;
            }
            set
            {
                this.OnmodifiedbyChanging(value);
                this._modifiedby = value;
                this.OnmodifiedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedby;
        partial void OnmodifiedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby
        {
            get
            {
                return this._modifiedonbehalfby;
            }
            set
            {
                this.OnmodifiedonbehalfbyChanging(value);
                this._modifiedonbehalfby = value;
                this.OnmodifiedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedonbehalfby;
        partial void OnmodifiedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property organizationid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.organization organizationid
        {
            get
            {
                return this._organizationid;
            }
            set
            {
                this.OnorganizationidChanging(value);
                this._organizationid = value;
                this.OnorganizationidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.organization _organizationid;
        partial void OnorganizationidChanging(global::Microsoft.Dynamics.CRM.organization value);
        partial void OnorganizationidChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> msdyn_adaptivecardconfiguration_SyncErrors
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_SyncErrors;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_SyncErrorsChanging(value);
                this._msdyn_adaptivecardconfiguration_SyncErrors = value;
                this.Onmsdyn_adaptivecardconfiguration_SyncErrorsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> _msdyn_adaptivecardconfiguration_SyncErrors = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror>();
        partial void Onmsdyn_adaptivecardconfiguration_SyncErrorsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> value);
        partial void Onmsdyn_adaptivecardconfiguration_SyncErrorsChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> msdyn_adaptivecardconfiguration_AsyncOperations
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_AsyncOperations;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_AsyncOperationsChanging(value);
                this._msdyn_adaptivecardconfiguration_AsyncOperations = value;
                this.Onmsdyn_adaptivecardconfiguration_AsyncOperationsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> _msdyn_adaptivecardconfiguration_AsyncOperations = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation>();
        partial void Onmsdyn_adaptivecardconfiguration_AsyncOperationsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> value);
        partial void Onmsdyn_adaptivecardconfiguration_AsyncOperationsChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> msdyn_adaptivecardconfiguration_MailboxTrackingFolders
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_MailboxTrackingFolders;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_MailboxTrackingFoldersChanging(value);
                this._msdyn_adaptivecardconfiguration_MailboxTrackingFolders = value;
                this.Onmsdyn_adaptivecardconfiguration_MailboxTrackingFoldersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _msdyn_adaptivecardconfiguration_MailboxTrackingFolders = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>();
        partial void Onmsdyn_adaptivecardconfiguration_MailboxTrackingFoldersChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> value);
        partial void Onmsdyn_adaptivecardconfiguration_MailboxTrackingFoldersChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_ProcessSession in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> msdyn_adaptivecardconfiguration_ProcessSession
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_ProcessSession;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_ProcessSessionChanging(value);
                this._msdyn_adaptivecardconfiguration_ProcessSession = value;
                this.Onmsdyn_adaptivecardconfiguration_ProcessSessionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> _msdyn_adaptivecardconfiguration_ProcessSession = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession>();
        partial void Onmsdyn_adaptivecardconfiguration_ProcessSessionChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> value);
        partial void Onmsdyn_adaptivecardconfiguration_ProcessSessionChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> msdyn_adaptivecardconfiguration_BulkDeleteFailures
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_BulkDeleteFailures;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_BulkDeleteFailuresChanging(value);
                this._msdyn_adaptivecardconfiguration_BulkDeleteFailures = value;
                this.Onmsdyn_adaptivecardconfiguration_BulkDeleteFailuresChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _msdyn_adaptivecardconfiguration_BulkDeleteFailures = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure>();
        partial void Onmsdyn_adaptivecardconfiguration_BulkDeleteFailuresChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> value);
        partial void Onmsdyn_adaptivecardconfiguration_BulkDeleteFailuresChanged();
        /// <summary>
        /// There are no comments for Property msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses
        {
            get
            {
                return this._msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses;
            }
            set
            {
                this.Onmsdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccessesChanging(value);
                this._msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses = value;
                this.Onmsdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccessesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _msdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccesses = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>();
        partial void Onmsdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccessesChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> value);
        partial void Onmsdyn_adaptivecardconfiguration_PrincipalObjectAttributeAccessesChanged();
    }
}
