//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2021-02-15 3:55:30 PM
namespace Microsoft.Dynamics.CRM
{
        /// <summary>
        /// There are no comments for msdyn_analysiscomponentSingle in the schema.
        /// </summary>
    public partial class msdyn_analysiscomponentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<msdyn_analysiscomponent>
    {
        /// <summary>
        /// Initialize a new msdyn_analysiscomponentSingle object.
        /// </summary>
        public msdyn_analysiscomponentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new msdyn_analysiscomponentSingle object.
        /// </summary>
        public msdyn_analysiscomponentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new msdyn_analysiscomponentSingle object.
        /// </summary>
        public msdyn_analysiscomponentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<msdyn_analysiscomponent> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdby == null))
                {
                    this._createdby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdby"));
                }
                return this._createdby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdby;
        /// <summary>
        /// There are no comments for createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle createdonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._createdonbehalfby == null))
                {
                    this._createdonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("createdonbehalfby"));
                }
                return this._createdonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _createdonbehalfby;
        /// <summary>
        /// There are no comments for modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedby == null))
                {
                    this._modifiedby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedby"));
                }
                return this._modifiedby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedby;
        /// <summary>
        /// There are no comments for modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle modifiedonbehalfby
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._modifiedonbehalfby == null))
                {
                    this._modifiedonbehalfby = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("modifiedonbehalfby"));
                }
                return this._modifiedonbehalfby;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _modifiedonbehalfby;
        /// <summary>
        /// There are no comments for owninguser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuserSingle owninguser
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._owninguser == null))
                {
                    this._owninguser = new global::Microsoft.Dynamics.CRM.systemuserSingle(this.Context, GetPath("owninguser"));
                }
                return this._owninguser;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuserSingle _owninguser;
        /// <summary>
        /// There are no comments for owningteam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.teamSingle owningteam
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._owningteam == null))
                {
                    this._owningteam = new global::Microsoft.Dynamics.CRM.teamSingle(this.Context, GetPath("owningteam"));
                }
                return this._owningteam;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.teamSingle _owningteam;
        /// <summary>
        /// There are no comments for ownerid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.principalSingle ownerid
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ownerid == null))
                {
                    this._ownerid = new global::Microsoft.Dynamics.CRM.principalSingle(this.Context, GetPath("ownerid"));
                }
                return this._ownerid;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.principalSingle _ownerid;
        /// <summary>
        /// There are no comments for owningbusinessunit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.businessunitSingle owningbusinessunit
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._owningbusinessunit == null))
                {
                    this._owningbusinessunit = new global::Microsoft.Dynamics.CRM.businessunitSingle(this.Context, GetPath("owningbusinessunit"));
                }
                return this._owningbusinessunit;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.businessunitSingle _owningbusinessunit;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> msdyn_analysiscomponent_SyncErrors
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_SyncErrors == null))
                {
                    this._msdyn_analysiscomponent_SyncErrors = Context.CreateQuery<global::Microsoft.Dynamics.CRM.syncerror>(GetPath("msdyn_analysiscomponent_SyncErrors"));
                }
                return this._msdyn_analysiscomponent_SyncErrors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.syncerror> _msdyn_analysiscomponent_SyncErrors;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_DuplicateMatchingRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.duplicaterecord> msdyn_analysiscomponent_DuplicateMatchingRecord
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_DuplicateMatchingRecord == null))
                {
                    this._msdyn_analysiscomponent_DuplicateMatchingRecord = Context.CreateQuery<global::Microsoft.Dynamics.CRM.duplicaterecord>(GetPath("msdyn_analysiscomponent_DuplicateMatchingRecord"));
                }
                return this._msdyn_analysiscomponent_DuplicateMatchingRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.duplicaterecord> _msdyn_analysiscomponent_DuplicateMatchingRecord;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_DuplicateBaseRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.duplicaterecord> msdyn_analysiscomponent_DuplicateBaseRecord
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_DuplicateBaseRecord == null))
                {
                    this._msdyn_analysiscomponent_DuplicateBaseRecord = Context.CreateQuery<global::Microsoft.Dynamics.CRM.duplicaterecord>(GetPath("msdyn_analysiscomponent_DuplicateBaseRecord"));
                }
                return this._msdyn_analysiscomponent_DuplicateBaseRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.duplicaterecord> _msdyn_analysiscomponent_DuplicateBaseRecord;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> msdyn_analysiscomponent_AsyncOperations
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_AsyncOperations == null))
                {
                    this._msdyn_analysiscomponent_AsyncOperations = Context.CreateQuery<global::Microsoft.Dynamics.CRM.asyncoperation>(GetPath("msdyn_analysiscomponent_AsyncOperations"));
                }
                return this._msdyn_analysiscomponent_AsyncOperations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.asyncoperation> _msdyn_analysiscomponent_AsyncOperations;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> msdyn_analysiscomponent_MailboxTrackingFolders
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_MailboxTrackingFolders == null))
                {
                    this._msdyn_analysiscomponent_MailboxTrackingFolders = Context.CreateQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>(GetPath("msdyn_analysiscomponent_MailboxTrackingFolders"));
                }
                return this._msdyn_analysiscomponent_MailboxTrackingFolders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _msdyn_analysiscomponent_MailboxTrackingFolders;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_ProcessSession in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> msdyn_analysiscomponent_ProcessSession
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_ProcessSession == null))
                {
                    this._msdyn_analysiscomponent_ProcessSession = Context.CreateQuery<global::Microsoft.Dynamics.CRM.processsession>(GetPath("msdyn_analysiscomponent_ProcessSession"));
                }
                return this._msdyn_analysiscomponent_ProcessSession;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.processsession> _msdyn_analysiscomponent_ProcessSession;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> msdyn_analysiscomponent_BulkDeleteFailures
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_BulkDeleteFailures == null))
                {
                    this._msdyn_analysiscomponent_BulkDeleteFailures = Context.CreateQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure>(GetPath("msdyn_analysiscomponent_BulkDeleteFailures"));
                }
                return this._msdyn_analysiscomponent_BulkDeleteFailures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _msdyn_analysiscomponent_BulkDeleteFailures;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> msdyn_analysiscomponent_PrincipalObjectAttributeAccesses
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_PrincipalObjectAttributeAccesses == null))
                {
                    this._msdyn_analysiscomponent_PrincipalObjectAttributeAccesses = Context.CreateQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>(GetPath("msdyn_analysiscomponent_PrincipalObjectAttributeAccesses"));
                }
                return this._msdyn_analysiscomponent_PrincipalObjectAttributeAccesses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _msdyn_analysiscomponent_PrincipalObjectAttributeAccesses;
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent_msdyn_analysisresult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.msdyn_analysisresult> msdyn_analysiscomponent_msdyn_analysisresult
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_analysiscomponent_msdyn_analysisresult == null))
                {
                    this._msdyn_analysiscomponent_msdyn_analysisresult = Context.CreateQuery<global::Microsoft.Dynamics.CRM.msdyn_analysisresult>(GetPath("msdyn_analysiscomponent_msdyn_analysisresult"));
                }
                return this._msdyn_analysiscomponent_msdyn_analysisresult;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.msdyn_analysisresult> _msdyn_analysiscomponent_msdyn_analysisresult;
        /// <summary>
        /// There are no comments for msdyn_AnalysisJobId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.msdyn_analysisjobSingle msdyn_AnalysisJobId
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_AnalysisJobId == null))
                {
                    this._msdyn_AnalysisJobId = new global::Microsoft.Dynamics.CRM.msdyn_analysisjobSingle(this.Context, GetPath("msdyn_AnalysisJobId"));
                }
                return this._msdyn_AnalysisJobId;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.msdyn_analysisjobSingle _msdyn_AnalysisJobId;
        /// <summary>
        /// There are no comments for msdyn_SolutionHealthRuleSetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.msdyn_solutionhealthrulesetSingle msdyn_SolutionHealthRuleSetId
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._msdyn_SolutionHealthRuleSetId == null))
                {
                    this._msdyn_SolutionHealthRuleSetId = new global::Microsoft.Dynamics.CRM.msdyn_solutionhealthrulesetSingle(this.Context, GetPath("msdyn_SolutionHealthRuleSetId"));
                }
                return this._msdyn_SolutionHealthRuleSetId;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.msdyn_solutionhealthrulesetSingle _msdyn_SolutionHealthRuleSetId;
    }
        /// <summary>
        /// There are no comments for msdyn_analysiscomponent in the schema.
        /// </summary>
    /// <KeyProperties>
    /// msdyn_analysiscomponentid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("msdyn_analysiscomponentid")]
    public partial class msdyn_analysiscomponent : crmbaseentity
    {
        /// <summary>
        /// Create a new msdyn_analysiscomponent object.
        /// </summary>
        /// <param name="createdby">Initial value of createdby.</param>
        /// <param name="createdonbehalfby">Initial value of createdonbehalfby.</param>
        /// <param name="modifiedby">Initial value of modifiedby.</param>
        /// <param name="modifiedonbehalfby">Initial value of modifiedonbehalfby.</param>
        /// <param name="owninguser">Initial value of owninguser.</param>
        /// <param name="owningteam">Initial value of owningteam.</param>
        /// <param name="ownerid">Initial value of ownerid.</param>
        /// <param name="owningbusinessunit">Initial value of owningbusinessunit.</param>
        /// <param name="msdyn_AnalysisJobId">Initial value of msdyn_AnalysisJobId.</param>
        /// <param name="msdyn_SolutionHealthRuleSetId">Initial value of msdyn_SolutionHealthRuleSetId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static msdyn_analysiscomponent Createmsdyn_analysiscomponent(global::Microsoft.Dynamics.CRM.systemuser createdby, 
                    global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby, 
                    global::Microsoft.Dynamics.CRM.systemuser modifiedby, 
                    global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby, 
                    global::Microsoft.Dynamics.CRM.systemuser owninguser, 
                    global::Microsoft.Dynamics.CRM.team owningteam, 
                    global::Microsoft.Dynamics.CRM.principal ownerid, 
                    global::Microsoft.Dynamics.CRM.businessunit owningbusinessunit, 
                    global::Microsoft.Dynamics.CRM.msdyn_analysisjob msdyn_AnalysisJobId, 
                    global::Microsoft.Dynamics.CRM.msdyn_solutionhealthruleset msdyn_SolutionHealthRuleSetId)
        {
            msdyn_analysiscomponent msdyn_analysiscomponent = new msdyn_analysiscomponent();
            if ((createdby == null))
            {
                throw new global::System.ArgumentNullException("createdby");
            }
            msdyn_analysiscomponent.createdby = createdby;
            if ((createdonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("createdonbehalfby");
            }
            msdyn_analysiscomponent.createdonbehalfby = createdonbehalfby;
            if ((modifiedby == null))
            {
                throw new global::System.ArgumentNullException("modifiedby");
            }
            msdyn_analysiscomponent.modifiedby = modifiedby;
            if ((modifiedonbehalfby == null))
            {
                throw new global::System.ArgumentNullException("modifiedonbehalfby");
            }
            msdyn_analysiscomponent.modifiedonbehalfby = modifiedonbehalfby;
            if ((owninguser == null))
            {
                throw new global::System.ArgumentNullException("owninguser");
            }
            msdyn_analysiscomponent.owninguser = owninguser;
            if ((owningteam == null))
            {
                throw new global::System.ArgumentNullException("owningteam");
            }
            msdyn_analysiscomponent.owningteam = owningteam;
            if ((ownerid == null))
            {
                throw new global::System.ArgumentNullException("ownerid");
            }
            msdyn_analysiscomponent.ownerid = ownerid;
            if ((owningbusinessunit == null))
            {
                throw new global::System.ArgumentNullException("owningbusinessunit");
            }
            msdyn_analysiscomponent.owningbusinessunit = owningbusinessunit;
            if ((msdyn_AnalysisJobId == null))
            {
                throw new global::System.ArgumentNullException("msdyn_AnalysisJobId");
            }
            msdyn_analysiscomponent.msdyn_AnalysisJobId = msdyn_AnalysisJobId;
            if ((msdyn_SolutionHealthRuleSetId == null))
            {
                throw new global::System.ArgumentNullException("msdyn_SolutionHealthRuleSetId");
            }
            msdyn_analysiscomponent.msdyn_SolutionHealthRuleSetId = msdyn_SolutionHealthRuleSetId;
            return msdyn_analysiscomponent;
        }
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponentid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> msdyn_analysiscomponentid
        {
            get
            {
                return this._msdyn_analysiscomponentid;
            }
            set
            {
                this.Onmsdyn_analysiscomponentidChanging(value);
                this._msdyn_analysiscomponentid = value;
                this.Onmsdyn_analysiscomponentidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _msdyn_analysiscomponentid;
        partial void Onmsdyn_analysiscomponentidChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onmsdyn_analysiscomponentidChanged();
        /// <summary>
        /// There are no comments for Property msdyn_componentid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_componentid
        {
            get
            {
                return this._msdyn_componentid;
            }
            set
            {
                this.Onmsdyn_componentidChanging(value);
                this._msdyn_componentid = value;
                this.Onmsdyn_componentidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_componentid;
        partial void Onmsdyn_componentidChanging(string value);
        partial void Onmsdyn_componentidChanged();
        /// <summary>
        /// There are no comments for Property _modifiedby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedby_value
        {
            get
            {
                return this.__modifiedby_value;
            }
            set
            {
                this.On_modifiedby_valueChanging(value);
                this.__modifiedby_value = value;
                this.On_modifiedby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedby_value;
        partial void On_modifiedby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedby_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_rulepasscount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_rulepasscount
        {
            get
            {
                return this._msdyn_rulepasscount;
            }
            set
            {
                this.Onmsdyn_rulepasscountChanging(value);
                this._msdyn_rulepasscount = value;
                this.Onmsdyn_rulepasscountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_rulepasscount;
        partial void Onmsdyn_rulepasscountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_rulepasscountChanged();
        /// <summary>
        /// There are no comments for Property versionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<long> versionnumber
        {
            get
            {
                return this._versionnumber;
            }
            set
            {
                this.OnversionnumberChanging(value);
                this._versionnumber = value;
                this.OnversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _versionnumber;
        partial void OnversionnumberChanging(global::System.Nullable<long> value);
        partial void OnversionnumberChanged();
        /// <summary>
        /// There are no comments for Property _msdyn_solutionhealthrulesetid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _msdyn_solutionhealthrulesetid_value
        {
            get
            {
                return this.__msdyn_solutionhealthrulesetid_value;
            }
            set
            {
                this.On_msdyn_solutionhealthrulesetid_valueChanging(value);
                this.__msdyn_solutionhealthrulesetid_value = value;
                this.On_msdyn_solutionhealthrulesetid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __msdyn_solutionhealthrulesetid_value;
        partial void On_msdyn_solutionhealthrulesetid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_msdyn_solutionhealthrulesetid_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_sevcriticalcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_sevcriticalcount
        {
            get
            {
                return this._msdyn_sevcriticalcount;
            }
            set
            {
                this.Onmsdyn_sevcriticalcountChanging(value);
                this._msdyn_sevcriticalcount = value;
                this.Onmsdyn_sevcriticalcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_sevcriticalcount;
        partial void Onmsdyn_sevcriticalcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_sevcriticalcountChanged();
        /// <summary>
        /// There are no comments for Property _createdonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdonbehalfby_value
        {
            get
            {
                return this.__createdonbehalfby_value;
            }
            set
            {
                this.On_createdonbehalfby_valueChanging(value);
                this.__createdonbehalfby_value = value;
                this.On_createdonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdonbehalfby_value;
        partial void On_createdonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property _modifiedonbehalfby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _modifiedonbehalfby_value
        {
            get
            {
                return this.__modifiedonbehalfby_value;
            }
            set
            {
                this.On_modifiedonbehalfby_valueChanging(value);
                this.__modifiedonbehalfby_value = value;
                this.On_modifiedonbehalfby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __modifiedonbehalfby_value;
        partial void On_modifiedonbehalfby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_modifiedonbehalfby_valueChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property modifiedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> modifiedon
        {
            get
            {
                return this._modifiedon;
            }
            set
            {
                this.OnmodifiedonChanging(value);
                this._modifiedon = value;
                this.OnmodifiedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _modifiedon;
        partial void OnmodifiedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnmodifiedonChanged();
        /// <summary>
        /// There are no comments for Property overriddencreatedon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> overriddencreatedon
        {
            get
            {
                return this._overriddencreatedon;
            }
            set
            {
                this.OnoverriddencreatedonChanging(value);
                this._overriddencreatedon = value;
                this.OnoverriddencreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _overriddencreatedon;
        partial void OnoverriddencreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnoverriddencreatedonChanged();
        /// <summary>
        /// There are no comments for Property msdyn_rulepassrate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_rulepassrate
        {
            get
            {
                return this._msdyn_rulepassrate;
            }
            set
            {
                this.Onmsdyn_rulepassrateChanging(value);
                this._msdyn_rulepassrate = value;
                this.Onmsdyn_rulepassrateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_rulepassrate;
        partial void Onmsdyn_rulepassrateChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_rulepassrateChanged();
        /// <summary>
        /// There are no comments for Property utcconversiontimezonecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> utcconversiontimezonecode
        {
            get
            {
                return this._utcconversiontimezonecode;
            }
            set
            {
                this.OnutcconversiontimezonecodeChanging(value);
                this._utcconversiontimezonecode = value;
                this.OnutcconversiontimezonecodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _utcconversiontimezonecode;
        partial void OnutcconversiontimezonecodeChanging(global::System.Nullable<int> value);
        partial void OnutcconversiontimezonecodeChanged();
        /// <summary>
        /// There are no comments for Property _msdyn_analysisjobid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _msdyn_analysisjobid_value
        {
            get
            {
                return this.__msdyn_analysisjobid_value;
            }
            set
            {
                this.On_msdyn_analysisjobid_valueChanging(value);
                this.__msdyn_analysisjobid_value = value;
                this.On_msdyn_analysisjobid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __msdyn_analysisjobid_value;
        partial void On_msdyn_analysisjobid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_msdyn_analysisjobid_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_retrycount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_retrycount
        {
            get
            {
                return this._msdyn_retrycount;
            }
            set
            {
                this.Onmsdyn_retrycountChanging(value);
                this._msdyn_retrycount = value;
                this.Onmsdyn_retrycountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_retrycount;
        partial void Onmsdyn_retrycountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_retrycountChanged();
        /// <summary>
        /// There are no comments for Property createdon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> createdon
        {
            get
            {
                return this._createdon;
            }
            set
            {
                this.OncreatedonChanging(value);
                this._createdon = value;
                this.OncreatedonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _createdon;
        partial void OncreatedonChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OncreatedonChanged();
        /// <summary>
        /// There are no comments for Property msdyn_componentversion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_componentversion
        {
            get
            {
                return this._msdyn_componentversion;
            }
            set
            {
                this.Onmsdyn_componentversionChanging(value);
                this._msdyn_componentversion = value;
                this.Onmsdyn_componentversionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_componentversion;
        partial void Onmsdyn_componentversionChanging(string value);
        partial void Onmsdyn_componentversionChanged();
        /// <summary>
        /// There are no comments for Property _owninguser_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _owninguser_value
        {
            get
            {
                return this.__owninguser_value;
            }
            set
            {
                this.On_owninguser_valueChanging(value);
                this.__owninguser_value = value;
                this.On_owninguser_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __owninguser_value;
        partial void On_owninguser_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_owninguser_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_componenttype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_componenttype
        {
            get
            {
                return this._msdyn_componenttype;
            }
            set
            {
                this.Onmsdyn_componenttypeChanging(value);
                this._msdyn_componenttype = value;
                this.Onmsdyn_componenttypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_componenttype;
        partial void Onmsdyn_componenttypeChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_componenttypeChanged();
        /// <summary>
        /// There are no comments for Property msdyn_componentname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_componentname
        {
            get
            {
                return this._msdyn_componentname;
            }
            set
            {
                this.Onmsdyn_componentnameChanging(value);
                this._msdyn_componentname = value;
                this.Onmsdyn_componentnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_componentname;
        partial void Onmsdyn_componentnameChanging(string value);
        partial void Onmsdyn_componentnameChanged();
        /// <summary>
        /// There are no comments for Property msdyn_sevhighcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_sevhighcount
        {
            get
            {
                return this._msdyn_sevhighcount;
            }
            set
            {
                this.Onmsdyn_sevhighcountChanging(value);
                this._msdyn_sevhighcount = value;
                this.Onmsdyn_sevhighcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_sevhighcount;
        partial void Onmsdyn_sevhighcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_sevhighcountChanged();
        /// <summary>
        /// There are no comments for Property msdyn_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string msdyn_name
        {
            get
            {
                return this._msdyn_name;
            }
            set
            {
                this.Onmsdyn_nameChanging(value);
                this._msdyn_name = value;
                this.Onmsdyn_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _msdyn_name;
        partial void Onmsdyn_nameChanging(string value);
        partial void Onmsdyn_nameChanged();
        /// <summary>
        /// There are no comments for Property _ownerid_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _ownerid_value
        {
            get
            {
                return this.__ownerid_value;
            }
            set
            {
                this.On_ownerid_valueChanging(value);
                this.__ownerid_value = value;
                this.On_ownerid_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __ownerid_value;
        partial void On_ownerid_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_ownerid_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_sevmediumcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_sevmediumcount
        {
            get
            {
                return this._msdyn_sevmediumcount;
            }
            set
            {
                this.Onmsdyn_sevmediumcountChanging(value);
                this._msdyn_sevmediumcount = value;
                this.Onmsdyn_sevmediumcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_sevmediumcount;
        partial void Onmsdyn_sevmediumcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_sevmediumcountChanged();
        /// <summary>
        /// There are no comments for Property _owningteam_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _owningteam_value
        {
            get
            {
                return this.__owningteam_value;
            }
            set
            {
                this.On_owningteam_valueChanging(value);
                this.__owningteam_value = value;
                this.On_owningteam_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __owningteam_value;
        partial void On_owningteam_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_owningteam_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_sevlowcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_sevlowcount
        {
            get
            {
                return this._msdyn_sevlowcount;
            }
            set
            {
                this.Onmsdyn_sevlowcountChanging(value);
                this._msdyn_sevlowcount = value;
                this.Onmsdyn_sevlowcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_sevlowcount;
        partial void Onmsdyn_sevlowcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_sevlowcountChanged();
        /// <summary>
        /// There are no comments for Property _createdby_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _createdby_value
        {
            get
            {
                return this.__createdby_value;
            }
            set
            {
                this.On_createdby_valueChanging(value);
                this.__createdby_value = value;
                this.On_createdby_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __createdby_value;
        partial void On_createdby_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_createdby_valueChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponenttype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_analysiscomponenttype
        {
            get
            {
                return this._msdyn_analysiscomponenttype;
            }
            set
            {
                this.Onmsdyn_analysiscomponenttypeChanging(value);
                this._msdyn_analysiscomponenttype = value;
                this.Onmsdyn_analysiscomponenttypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_analysiscomponenttype;
        partial void Onmsdyn_analysiscomponenttypeChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_analysiscomponenttypeChanged();
        /// <summary>
        /// There are no comments for Property msdyn_warningcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_warningcount
        {
            get
            {
                return this._msdyn_warningcount;
            }
            set
            {
                this.Onmsdyn_warningcountChanging(value);
                this._msdyn_warningcount = value;
                this.Onmsdyn_warningcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_warningcount;
        partial void Onmsdyn_warningcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_warningcountChanged();
        /// <summary>
        /// There are no comments for Property _owningbusinessunit_value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> _owningbusinessunit_value
        {
            get
            {
                return this.__owningbusinessunit_value;
            }
            set
            {
                this.On_owningbusinessunit_valueChanging(value);
                this.__owningbusinessunit_value = value;
                this.On_owningbusinessunit_valueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> __owningbusinessunit_value;
        partial void On_owningbusinessunit_valueChanging(global::System.Nullable<global::System.Guid> value);
        partial void On_owningbusinessunit_valueChanged();
        /// <summary>
        /// There are no comments for Property timezoneruleversionnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> timezoneruleversionnumber
        {
            get
            {
                return this._timezoneruleversionnumber;
            }
            set
            {
                this.OntimezoneruleversionnumberChanging(value);
                this._timezoneruleversionnumber = value;
                this.OntimezoneruleversionnumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _timezoneruleversionnumber;
        partial void OntimezoneruleversionnumberChanging(global::System.Nullable<int> value);
        partial void OntimezoneruleversionnumberChanged();
        /// <summary>
        /// There are no comments for Property importsequencenumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> importsequencenumber
        {
            get
            {
                return this._importsequencenumber;
            }
            set
            {
                this.OnimportsequencenumberChanging(value);
                this._importsequencenumber = value;
                this.OnimportsequencenumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _importsequencenumber;
        partial void OnimportsequencenumberChanging(global::System.Nullable<int> value);
        partial void OnimportsequencenumberChanged();
        /// <summary>
        /// There are no comments for Property msdyn_errorcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_errorcount
        {
            get
            {
                return this._msdyn_errorcount;
            }
            set
            {
                this.Onmsdyn_errorcountChanging(value);
                this._msdyn_errorcount = value;
                this.Onmsdyn_errorcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_errorcount;
        partial void Onmsdyn_errorcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_errorcountChanged();
        /// <summary>
        /// There are no comments for Property msdyn_rulefailcount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> msdyn_rulefailcount
        {
            get
            {
                return this._msdyn_rulefailcount;
            }
            set
            {
                this.Onmsdyn_rulefailcountChanging(value);
                this._msdyn_rulefailcount = value;
                this.Onmsdyn_rulefailcountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _msdyn_rulefailcount;
        partial void Onmsdyn_rulefailcountChanging(global::System.Nullable<int> value);
        partial void Onmsdyn_rulefailcountChanged();
        /// <summary>
        /// There are no comments for Property createdby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdby
        {
            get
            {
                return this._createdby;
            }
            set
            {
                this.OncreatedbyChanging(value);
                this._createdby = value;
                this.OncreatedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdby;
        partial void OncreatedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedbyChanged();
        /// <summary>
        /// There are no comments for Property createdonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser createdonbehalfby
        {
            get
            {
                return this._createdonbehalfby;
            }
            set
            {
                this.OncreatedonbehalfbyChanging(value);
                this._createdonbehalfby = value;
                this.OncreatedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _createdonbehalfby;
        partial void OncreatedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OncreatedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedby
        {
            get
            {
                return this._modifiedby;
            }
            set
            {
                this.OnmodifiedbyChanging(value);
                this._modifiedby = value;
                this.OnmodifiedbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedby;
        partial void OnmodifiedbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedbyChanged();
        /// <summary>
        /// There are no comments for Property modifiedonbehalfby in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser modifiedonbehalfby
        {
            get
            {
                return this._modifiedonbehalfby;
            }
            set
            {
                this.OnmodifiedonbehalfbyChanging(value);
                this._modifiedonbehalfby = value;
                this.OnmodifiedonbehalfbyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _modifiedonbehalfby;
        partial void OnmodifiedonbehalfbyChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnmodifiedonbehalfbyChanged();
        /// <summary>
        /// There are no comments for Property owninguser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.systemuser owninguser
        {
            get
            {
                return this._owninguser;
            }
            set
            {
                this.OnowninguserChanging(value);
                this._owninguser = value;
                this.OnowninguserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.systemuser _owninguser;
        partial void OnowninguserChanging(global::Microsoft.Dynamics.CRM.systemuser value);
        partial void OnowninguserChanged();
        /// <summary>
        /// There are no comments for Property owningteam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.team owningteam
        {
            get
            {
                return this._owningteam;
            }
            set
            {
                this.OnowningteamChanging(value);
                this._owningteam = value;
                this.OnowningteamChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.team _owningteam;
        partial void OnowningteamChanging(global::Microsoft.Dynamics.CRM.team value);
        partial void OnowningteamChanged();
        /// <summary>
        /// There are no comments for Property ownerid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.principal ownerid
        {
            get
            {
                return this._ownerid;
            }
            set
            {
                this.OnowneridChanging(value);
                this._ownerid = value;
                this.OnowneridChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.principal _ownerid;
        partial void OnowneridChanging(global::Microsoft.Dynamics.CRM.principal value);
        partial void OnowneridChanged();
        /// <summary>
        /// There are no comments for Property owningbusinessunit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.businessunit owningbusinessunit
        {
            get
            {
                return this._owningbusinessunit;
            }
            set
            {
                this.OnowningbusinessunitChanging(value);
                this._owningbusinessunit = value;
                this.OnowningbusinessunitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.businessunit _owningbusinessunit;
        partial void OnowningbusinessunitChanging(global::Microsoft.Dynamics.CRM.businessunit value);
        partial void OnowningbusinessunitChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_SyncErrors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> msdyn_analysiscomponent_SyncErrors
        {
            get
            {
                return this._msdyn_analysiscomponent_SyncErrors;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_SyncErrorsChanging(value);
                this._msdyn_analysiscomponent_SyncErrors = value;
                this.Onmsdyn_analysiscomponent_SyncErrorsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> _msdyn_analysiscomponent_SyncErrors = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror>();
        partial void Onmsdyn_analysiscomponent_SyncErrorsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.syncerror> value);
        partial void Onmsdyn_analysiscomponent_SyncErrorsChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_DuplicateMatchingRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> msdyn_analysiscomponent_DuplicateMatchingRecord
        {
            get
            {
                return this._msdyn_analysiscomponent_DuplicateMatchingRecord;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_DuplicateMatchingRecordChanging(value);
                this._msdyn_analysiscomponent_DuplicateMatchingRecord = value;
                this.Onmsdyn_analysiscomponent_DuplicateMatchingRecordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> _msdyn_analysiscomponent_DuplicateMatchingRecord = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord>();
        partial void Onmsdyn_analysiscomponent_DuplicateMatchingRecordChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> value);
        partial void Onmsdyn_analysiscomponent_DuplicateMatchingRecordChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_DuplicateBaseRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> msdyn_analysiscomponent_DuplicateBaseRecord
        {
            get
            {
                return this._msdyn_analysiscomponent_DuplicateBaseRecord;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_DuplicateBaseRecordChanging(value);
                this._msdyn_analysiscomponent_DuplicateBaseRecord = value;
                this.Onmsdyn_analysiscomponent_DuplicateBaseRecordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> _msdyn_analysiscomponent_DuplicateBaseRecord = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord>();
        partial void Onmsdyn_analysiscomponent_DuplicateBaseRecordChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.duplicaterecord> value);
        partial void Onmsdyn_analysiscomponent_DuplicateBaseRecordChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_AsyncOperations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> msdyn_analysiscomponent_AsyncOperations
        {
            get
            {
                return this._msdyn_analysiscomponent_AsyncOperations;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_AsyncOperationsChanging(value);
                this._msdyn_analysiscomponent_AsyncOperations = value;
                this.Onmsdyn_analysiscomponent_AsyncOperationsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> _msdyn_analysiscomponent_AsyncOperations = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation>();
        partial void Onmsdyn_analysiscomponent_AsyncOperationsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.asyncoperation> value);
        partial void Onmsdyn_analysiscomponent_AsyncOperationsChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_MailboxTrackingFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> msdyn_analysiscomponent_MailboxTrackingFolders
        {
            get
            {
                return this._msdyn_analysiscomponent_MailboxTrackingFolders;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_MailboxTrackingFoldersChanging(value);
                this._msdyn_analysiscomponent_MailboxTrackingFolders = value;
                this.Onmsdyn_analysiscomponent_MailboxTrackingFoldersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> _msdyn_analysiscomponent_MailboxTrackingFolders = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder>();
        partial void Onmsdyn_analysiscomponent_MailboxTrackingFoldersChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.mailboxtrackingfolder> value);
        partial void Onmsdyn_analysiscomponent_MailboxTrackingFoldersChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_ProcessSession in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> msdyn_analysiscomponent_ProcessSession
        {
            get
            {
                return this._msdyn_analysiscomponent_ProcessSession;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_ProcessSessionChanging(value);
                this._msdyn_analysiscomponent_ProcessSession = value;
                this.Onmsdyn_analysiscomponent_ProcessSessionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> _msdyn_analysiscomponent_ProcessSession = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession>();
        partial void Onmsdyn_analysiscomponent_ProcessSessionChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.processsession> value);
        partial void Onmsdyn_analysiscomponent_ProcessSessionChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_BulkDeleteFailures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> msdyn_analysiscomponent_BulkDeleteFailures
        {
            get
            {
                return this._msdyn_analysiscomponent_BulkDeleteFailures;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_BulkDeleteFailuresChanging(value);
                this._msdyn_analysiscomponent_BulkDeleteFailures = value;
                this.Onmsdyn_analysiscomponent_BulkDeleteFailuresChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> _msdyn_analysiscomponent_BulkDeleteFailures = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure>();
        partial void Onmsdyn_analysiscomponent_BulkDeleteFailuresChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.bulkdeletefailure> value);
        partial void Onmsdyn_analysiscomponent_BulkDeleteFailuresChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_PrincipalObjectAttributeAccesses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> msdyn_analysiscomponent_PrincipalObjectAttributeAccesses
        {
            get
            {
                return this._msdyn_analysiscomponent_PrincipalObjectAttributeAccesses;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_PrincipalObjectAttributeAccessesChanging(value);
                this._msdyn_analysiscomponent_PrincipalObjectAttributeAccesses = value;
                this.Onmsdyn_analysiscomponent_PrincipalObjectAttributeAccessesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> _msdyn_analysiscomponent_PrincipalObjectAttributeAccesses = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess>();
        partial void Onmsdyn_analysiscomponent_PrincipalObjectAttributeAccessesChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.principalobjectattributeaccess> value);
        partial void Onmsdyn_analysiscomponent_PrincipalObjectAttributeAccessesChanged();
        /// <summary>
        /// There are no comments for Property msdyn_analysiscomponent_msdyn_analysisresult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.msdyn_analysisresult> msdyn_analysiscomponent_msdyn_analysisresult
        {
            get
            {
                return this._msdyn_analysiscomponent_msdyn_analysisresult;
            }
            set
            {
                this.Onmsdyn_analysiscomponent_msdyn_analysisresultChanging(value);
                this._msdyn_analysiscomponent_msdyn_analysisresult = value;
                this.Onmsdyn_analysiscomponent_msdyn_analysisresultChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.msdyn_analysisresult> _msdyn_analysiscomponent_msdyn_analysisresult = new global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.msdyn_analysisresult>();
        partial void Onmsdyn_analysiscomponent_msdyn_analysisresultChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.Dynamics.CRM.msdyn_analysisresult> value);
        partial void Onmsdyn_analysiscomponent_msdyn_analysisresultChanged();
        /// <summary>
        /// There are no comments for Property msdyn_AnalysisJobId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.msdyn_analysisjob msdyn_AnalysisJobId
        {
            get
            {
                return this._msdyn_AnalysisJobId;
            }
            set
            {
                this.Onmsdyn_AnalysisJobIdChanging(value);
                this._msdyn_AnalysisJobId = value;
                this.Onmsdyn_AnalysisJobIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.msdyn_analysisjob _msdyn_AnalysisJobId;
        partial void Onmsdyn_AnalysisJobIdChanging(global::Microsoft.Dynamics.CRM.msdyn_analysisjob value);
        partial void Onmsdyn_AnalysisJobIdChanged();
        /// <summary>
        /// There are no comments for Property msdyn_SolutionHealthRuleSetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.CRM.msdyn_solutionhealthruleset msdyn_SolutionHealthRuleSetId
        {
            get
            {
                return this._msdyn_SolutionHealthRuleSetId;
            }
            set
            {
                this.Onmsdyn_SolutionHealthRuleSetIdChanging(value);
                this._msdyn_SolutionHealthRuleSetId = value;
                this.Onmsdyn_SolutionHealthRuleSetIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.CRM.msdyn_solutionhealthruleset _msdyn_SolutionHealthRuleSetId;
        partial void Onmsdyn_SolutionHealthRuleSetIdChanging(global::Microsoft.Dynamics.CRM.msdyn_solutionhealthruleset value);
        partial void Onmsdyn_SolutionHealthRuleSetIdChanged();
    }
}
